### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by cyanfish** [cyanfish/naps2#109]
- [ ] Windows - Blocker: #436
- [x] Mac
- [x] Linux

**Comment by ace280** [comment]
Yes please =D

**Comment by joshuadavidmcgee** [comment]
+1 for Windows Dark Mode Support

**Comment by cyanfish** [comment]
Mac and Linux should now support dark mode in [7.0b9](https://www.naps2.com/download). Windows won't happen for a while as it depends on #81.

**Comment by Unixware** [comment]
I think you may missed few parts of the code to change, eg things like the main background , also background of the scanner profiles and  of  the language chooser page (OCR)  are still 'white' , even when the dconf set the org.gnome.desktop.interface.color-scheme  as 'prefer-dark'  
tnx

**Comment by cyanfish** [comment]
@Unixware What distro and desktop environment are you using?

**Comment by Unixware** [comment]
sorry I should mention it, Gnome (on debian 12)

**Comment by cyanfish** [comment]
[7.1.0](https://www.naps2.com/download) has some improvements for dark theme detection that should resolve this.

**Comment by LinuxOnTheDesktop** [comment]
Hello!

I've 7.1.2 and . . it's all white on a Windows that is dark-themed.

**Comment by cloudmaker97** [comment]
> Hello!
> 
> I've 7.1.2 and . . it's all white on a Windows that is dark-themed.

Yeah, the implementation of this feature it's currently blocked by #81 

@cyanfish Could I assist you with the issue #81 in some way? Or do you plan it to do by yourself? 😊

**Comment by cyanfish** [comment]
Windows dark mode support has been added in [8.0b1](https://www.naps2.com/download).
