### ISSUE TITLE
Additional OCR modes possible?

### ISSUE THREAD

**Issue by NextTherapist** [cyanfish/naps2#114]
In the NAPS2 GUI (7.0b6) I can choose between "fast" and "best" OCR mode. Is is possible to choose something in the middle? The fast mode is not so accurate in some cases, and the best mode is very slow on my machine.

In the config.xml I found the line
`  <OcrMode>Best</OcrMode>`
Could I edit this line manually, and what additional options are possible?

**Comment by cyanfish** [comment]
Hi, unfortunately the OCR engine NAPS2 uses (Tesseract) only has those two options available.
