### ISSUE TITLE
Macos Intel: Error when scanning for SANE devices

### ISSUE THREAD

**Issue by rcnza** [cyanfish/naps2#116]
The error in the screenshot appears when scanning for devices using the SANE driver.  It does not happen in beta 5, only in beta 6.  It also does not happen with the Apple driver selected.  Intel mac running Big Sur.

Could not load library libsane.1.dylib

![naps2_7 06b_error](https://user-images.githubusercontent.com/59911079/225573210-4e10d7dd-aaf9-49bd-afd7-56164ec55ae1.png)

**Comment by cyanfish** [comment]
Please try the [latest beta (7.0b7)](https://www.naps2.com/download), I think it should be fixed.
