### ISSUE TITLE
Importing computer fax pdf file leads to black background

### ISSUE THREAD

**Issue by NextTherapist** [cyanfish/naps2#117]
This attached fax pdf file was generated by a router after receiving a fax. All these auto-generated fax files produce a black background when imported into NAPS2. 

Could this be changed? I have no influence on file generation...

[fax test file.pdf](https://github.com/cyanfish/naps2/files/10998893/fax.test.file.pdf)

**Comment by cyanfish** [comment]
This should be fixed in the [latest beta (7.0b7)](https://www.naps2.com/download).

**Comment by NextTherapist** [comment]
Thank you!
