### ISSUE TITLE
Sdk worker management

### ISSUE THREAD

**Issue by fronbasal** [cyanfish/naps2#121]
**Describe the bug**
I am unable to list devices using the Sdk on Mac, as I am unsure what IWorkerFactory implementation to pass to the ScannerManager, thus failing the `GetDeviceList` call.

**Expected behavior**
Maybe an example on how to interface NAPS2's SDK on MacOS.

**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - Version master

**Comment by cyanfish** [comment]
Worker management is one of the reasons NAPS2.Sdk is currently a "work in progress" and not quite ready yet. But if you want to get it working without a worker you can patch [ScanBridgeFactory](https://github.com/cyanfish/naps2/blob/e042206a2152292235f5d1a81ccec363e4b37095/NAPS2.Sdk/Scan/Internal/ScanBridgeFactory.cs#L14) to always return InProcScanBridge.

**Comment by cyanfish** [comment]
I've publish the first alpha version of NAPS2.Sdk. Basic worker management should be functional (i.e. working without on Mac/Linux and available via the NAPS2.Sdk.Worker.Win32 package for TWAIN scanning on Windows).
