### ISSUE TITLE
More detailed OCR in PDF24 than in NAPS2 with the same Tesseract version

### ISSUE THREAD

**Issue by NextTherapist** [cyanfish/naps2#124]
Hi,

I found differences between OCR of PDF24 and NAPS2, both newest versions, both containing Tesseract 5.2.0, when doing OCR on the same black/white PDF file with a gridded background like a slight grey (background from a scanned form).

PDF24 detects small or pixelated characters better, and sometimes NAPS2 detects nothing at all instead. Both need the same amount of time.

Something must be different in the Tesseract integration of both softwares, since both say they use Tesseract 5.2.0. NAPS2 (7.0b7) is on "best" quality, PDF24 has no setting for quality.

Perhaps there is something that could be improved in the NAPS implementation of Tesseract?

**Comment by cyanfish** [comment]
I'll need a sample file with the issue to do a comparison.

**Comment by cyanfish** [comment]
I did a comparison and couldn't identify a significant quality difference. Feel free to attach a sample file that is significantly better in PDF24 and I'll have a look.
