### ISSUE TITLE
"Scan with a single click" (for batch and other/multiple profiles)

### ISSUE THREAD

**Issue by Savasdotexe** [cyanfish/naps2#144]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more of an improvement to enable "Scan with a single click" concept for multiple _profiles_, for example I sometimes like to scan images and save them to jpeg, sometimes I'd like to scan and reorder, sometimes at max quality resolution or sizes, add OCR, but most times I like to batch scan and select single or multiple on the fly.

**Describe the solution you'd like**
Allow to add multiple scan buttons on the top menu, so for example setting up a profile or the batch option beside the current "Scan" button and allowing a single click for that _profile_.

**Describe alternatives you've considered**
No alternative option to even one click scan and save as a jpeg. The only alternative is using hotkeys, which I can't see anywhere to customize (which could be a profile setting).

**Additional context**
Made a kind of example of what I mean (obviously the names/icons/colors can be different):
https://i.postimg.cc/GmfGt57X/screenshot-2023-05-07-120259.jpg

**Comment by cyanfish** [comment]
In [NAPS2 7.3.0](https://www.naps2.com/download) I've added a "Settings" window with a "Show Profiles toolbar" option that does something like this.
