### ISSUE TITLE
Multilingual text recognition

### ISSUE THREAD

**Issue by tomright** [cyanfish/naps2#161]
Is it possible to do multi-language recognition? For example, if you select Russian, the links are recognized incorrectly. I suggest adding English + the desired language.

**Comment by cyanfish** [comment]
It's not currently possible to do this from the NAPS2 interface. (Though you can technically do it from the [command line](https://www.naps2.com/doc/command-line#ocr-options).)

**Comment by cyanfish** [comment]
This was added in [NAPS2 7.4.0](https://www.naps2.com/download) (select "Multiple Languages" in the OCR dropdown).
