### ISSUE TITLE
NAPS2 SDK not available on Nuget.org

### ISSUE THREAD

**Issue by hansaliyad1** [cyanfish/naps2#175]
**Describe the bug**
NAPS2.SDK is not available on NuGet.org. I thought it was available from NuGet. The website (https://www.nuget.org/packages/NAPS2.Sdk/) is not reachable.

**Desktop (please complete the following information):**
 - OS: Windows 10,

**Comment by cyanfish** [comment]
Per the [readme](https://github.com/cyanfish/naps2/tree/master/NAPS2.Sdk):

> NAPS2.Sdk is a work in progress. Nuget packages will be made available once it is ready for public consumption.
