### ISSUE TITLE
[LINUX] After getting image in NAPS2 scanner is still in sending state

### ISSUE THREAD

**Issue by ShamanInCap** [cyanfish/naps2#176]
**Describe the bug**
After getting image in NAPS2 scanner of MFP Kyocera M2030dn is still in sending state. To scan again "Cancel" button must be pressed on MFP

**To Reproduce**
1. Installed latest official drivers for M2030dn
2. Installed SANE driver 2.0.0326 and configured /etc/sane.d/kyocera_devices.conf with model and IP address of MFP
3. Installed NAPS2 7.0b9
4. Created profile of MFP in NAPS2
5. Successfully scanned colored image
6. Couldn't make another scan, noticed that MFP still displaying "sending" on LCD
7. Scanned again with xsane - successful scan and no hanging of send state on MFP

**Desktop (please complete the following information):**
 - OS: Kubuntu 23.04

**Comment by cyanfish** [comment]
This should be fixed in [7.1.0](https://www.naps2.com/download); please let me know if that works for you.
