### ISSUE TITLE
7.0b9 crashes consistently when importing PDF

### ISSUE THREAD

**Issue by organist1216** [cyanfish/naps2#178]
**Describe the bug**
I recently updated to 7.0b9 and it crashes when I try to import a PDF. It does it across multiple files (all of which worked fine in previous versions of NAPS. There are no error messages or anything, it just abruptly closes. 

**To Reproduce**
1. click on "import PDF"
2. select PDF to import
3. program crashes at some point when importing

 - OS: Windows 11, 22H2
 - Version 22621.2134

**Comment by cyanfish** [comment]
Can you open the Windows [Event Viewer](https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/) and see if, under Application, there are any logs for the crash?

**Comment by organist1216** [comment]
Sorry for the delay... There is an error listed in Event Viewer. Here are some screenshots. 
![Screenshot 2023-08-29 175149](https://github.com/cyanfish/naps2/assets/127072963/a6d6bb49-12f6-428e-9623-58cfcbf150eb)

![Screenshot 2023-08-29 174913](https://github.com/cyanfish/naps2/assets/127072963/0f711fb4-46da-49bb-838f-e49c576ff939)
![Screenshot 2023-08-29 175035](https://github.com/cyanfish/naps2/assets/127072963/131035a2-d96c-4b2e-a17b-2bef13b5014d)
![Screenshot 2023-08-29 175048](https://github.com/cyanfish/naps2/assets/127072963/c0c474d7-5ec1-43ea-b846-0b90928fc46f)

**Comment by cyanfish** [comment]
Thanks, there's one entry below that one (labeled ".NET Runtime") that should have more info if you can screenshot that as well.

**Comment by organist1216** [comment]
Here it is. The highlighted bit of text in one of the screenshots was just for me to gauge how much I had to scroll to get everything in 2 screenshots. 

![Screenshot 2023-08-30 224652](https://github.c
![Screenshot 2023-08-30 224559](https://github.com/cyanfish/naps2/assets/127072963/92148bd5-0809-45d3-be88-47dbf0f04f19)
![Screenshot 2023-08-30 224552](https://github.com/cyanfish/naps2/assets/127072963/b384fbf5-4297-4763-922b-9ef0ce21eda4)
om/cyanfish/naps2/assets/127072963/6aca4102-ce36-4d49-bc9f-1a9e83905cdf)
![Screenshot 2023-08-30 224642](https://github.com/cyanfish/naps2/assets/127072963/5baca652-6808-4765-bbd3-6dae04cc1910)

Let me know if there is anything else...thanks for the hard work/responsiveness.

**Comment by organist1216** [comment]
Left out the last one for some reason...

![Screenshot 2023-08-30 224652](https://github.com/cyanfish/naps2/assets/127072963/9a0f29b8-1e72-45ba-be74-b0a46eff84eb)

**Comment by cyanfish** [comment]
Thanks, that's helpful. Is there a sample PDF with the problem that you'd be able to upload?

**Comment by organist1216** [comment]
I tested and it crashed with this one, though the original one that I was trying is too large to upload.

[Humility Of Heart.pdf](https://github.com/cyanfish/naps2/files/12482011/Humility.Of.Heart.pdf)

**Comment by cyanfish** [comment]
Thanks, that was enough for me to track the problem. It's definitely one that can be inconsistent. I'll have a fix in the next version.

**Comment by cyanfish** [comment]
This should be fixed in [7.1.0](https://www.naps2.com/download).

**Comment by organist1216** [comment]
Everything works perfectly now. Thank you very much!
