### ISSUE TITLE
Jp2 support for Windows

### ISSUE THREAD

**Issue by vivadavid** [cyanfish/naps2#184]
Hi,

The latest changelog says that JP2 support is pending for Windows. I just wanted to emphasize that it would be great to have it, as the source for many books in Archive.org is provided in the Jp2 format.

Thanks in advance!

**Comment by cyanfish** [comment]
I will keep that in mind!

(Closing this issue in favor of https://github.com/cyanfish/naps2/issues/101)

**Comment by vivadavid** [comment]
Sorry that I created a duplicated thread. I did search for "jp2", but I forgot "jpeg2000".
