### ISSUE TITLE
How to scan using default scanner without profile?

### ISSUE THREAD

**Issue by shahareldad** [cyanfish/naps2#185]
Hi
I wish to use the console application of naps.
I'm looking to scan with default scanner but I don't want to select a profile first.
I don't want the user to be forced to first configure.
I want the user to start using the command line immediately, and naps will start scanning using the first found scanner.

Is this possible?
Thanks

**Comment by cyanfish** [comment]
That's not currently possible, though you can use [NAPS2.Sdk](https://github.com/cyanfish/naps2/tree/master/NAPS2.Sdk) instead of the console app.

**Comment by shahareldad** [comment]
Thanks, I will try that
