### ISSUE TITLE
No icon for the portable Windows version

### ISSUE THREAD

**Issue by vivadavid** [cyanfish/naps2#187]
**Describe the bug**
At least the portable Windows version doesn't have an icon.

**Desktop (please complete the following information):**
 - OS: Windows 11, 22H2.
 - Version 7.1.0.

**Comment by cyanfish** [comment]
This should be fixed in [7.1.1](https://www.naps2.com/download).

**Comment by vivadavid** [comment]
> This should be fixed in [7.1.1](https://www.naps2.com/download).

Hi,

I've just tested it and it's certainly fixed. Thanks!
