### ISSUE TITLE
Unable to build a project with SDK version 0.1.0-alpha04 

### ISSUE THREAD

**Issue by martron1** [cyanfish/naps2#190]
Describe the bug
When I try building a project with the new version of NAPS2.Sdk (0.1.0-alpha04) I get an error "NU1101	Unable to find package NAPS2.Escl. No packages exist with this id in source(s): local, Microsoft Visual Studio Offline Packages, nuget.org"

To Reproduce
1. Create a project: " 
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
	<PackageReference Include="NAPS2.Sdk" Version="0.1.0-alpha04" />
    <PackageReference Include="NAPS2.Images" Version="0.1.0-alpha04" />
	<PackageReference Include="NAPS2.Images.Gdi" Version="0.1.0-alpha04" />
	<PackageReference Include="NAPS2.Sdk.Worker.Win32" Version="0.1.0-alpha04" />
  </ItemGroup>
</Project>
"
2. Create a minimal api application and add "
app.MapGet("", async () =>
{
    using ScanningContext scanningContext = new ScanningContext(new GdiImageContext());
    scanningContext.SetUpWin32Worker();
    var _scanController = new ScanController(scanningContext);

    var devices = await _scanController.GetDeviceList();
    return Results.Ok(devices);
});
"
3. The project will not build

Expected behavior:
To build the project

Desktop:
    OS: Windows 11 22H2

Additional context
It works fine on version 0.1.0-alpha03.

**Comment by cyanfish** [comment]
This should be fixed in alpha05.
