### ISSUE TITLE
NAPS2 now prevents system shutdown

### ISSUE THREAD

**Issue by lewri** [cyanfish/naps2#192]
**Describe the bug**
Following on the new releases of NAPS2 the software now can prevent system shutdown if the software has a document loaded but has already been saved.

**To Reproduce**
1. A document
2. Save document
3. Attempt to shutdown. Message received saying NAPS2 is preventing shutdown.

**Expected behavior**
Software should cleanly close with the computer on shutdown if there are no unsaved files. The old versions from ~2018 would shut down fine with the system

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version  (7.1.10)

**Additional context**

**Comment by cyanfish** [comment]
This should be fixed in [7.1.1](https://www.naps2.com/download).
