### ISSUE TITLE
allow console from portable mode.

### ISSUE THREAD

**Issue by BiatuAutMiahn** [cyanfish/naps2#193]
When attempting to auto scan with the console while using portable mode, it only launches the GUI.

**Comment by cyanfish** [comment]
You can use NAPS2.Console.exe which is inside the "App" folder.

**Comment by BiatuAutMiahn** [comment]
That's what I'm figured out but profiles aren't portable, or am I overlooking something?

**Comment by cyanfish** [comment]
The portable version uses profiles that are stored in the "Data" folder.

**Comment by BiatuAutMiahn** [comment]
Right but isn't the naps2.portable wrapper performing redirection? if so, running naps2.console directly  doesn't perform the redirection

**Comment by cyanfish** [comment]
No, it's just a launcher. Everything has a separate build for the portable that references the local folders instead of the user folders.

**Comment by BiatuAutMiahn** [comment]
Gotcha, thx
