### ISSUE TITLE
"Prompt for file path" selection window doesn't appear

### ISSUE THREAD

**Issue by felistime** [cyanfish/naps2#202]
**Describe the bug**

If "Prompt for file path" checkbox in autosave window inside the profile's settings is checked and i perform a scan, there's no window asking me to choose a file path after the scan has ended.
**To Reproduce**
1. Go to profile settings
2. Check "Enable autosave" checkbox and click Auto Save Settings
3. Set a file path (ex. C:\Users\me\test.pdf)
4. Do the scan
5 No file prompt window appears

**Expected behavior**
A file prompt window appears at the end of the scan, as in naps2 6.1.2, that seems to be the last working version for this feature.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 7.1.0, 7.0b9, 7.0b1

**Comment by cyanfish** [comment]
This should be fixed in [7.1.1](https://www.naps2.com/download).
