### ISSUE TITLE
Scan Profile Delete

### ISSUE THREAD

**Issue by vnnspace** [cyanfish/naps2#203]
Hello. 
I have a question. How can I delete a created Profile? 
I found only one option was to go to the 
*\AppData\Roaming\NAPS2\ and delete profiles file.
I think it should be a better way to do it.

**Comment by cyanfish** [comment]
Click the Profiles button, select the profile, and click the Delete button.

**Comment by vnnspace** [comment]
Thank you. 
I am all time push Scan button and can not understand why i can not delete it :-) 
Sorry for the stupid question.
