### ISSUE TITLE
Scan issue causing black border to be added around the scanned image

### ISSUE THREAD

**Issue by jahvari** [cyanfish/naps2#219]
**Describe the bug**
I believe to have an issue with the cropping of a scan. When a smaller sheet (smaller than a regular piece of paper) is scanned, a black border is put around the scan, rather than white space. The issue is when the image is printed, the black is still around the image causing much more black ink to be used. 

**Expected behavior**
In prior versions, white space would be around the image rather than the black border.

**Screenshots**
I will add screenshots shortly.

**Desktop (please complete the following information):**
 - Windows 10
 - Version 7.1.2

**Comment by cyanfish** [comment]
Can you add those screenshots when you get a chance? What driver (twain/wia) are you using? What scanner model? Can you confirm that it's different between version 6.1.2 (or whatever prior version) and 7.1.2?

**Comment by jahvari** [comment]
@cyanfish Attached are the screenshots from 7.1.2

![Settings #1](https://github.com/cyanfish/naps2/assets/75337667/4579cb7e-04cd-478a-a83e-216a45fa2e4a)

![Settings #1 Scan](https://github.com/cyanfish/naps2/assets/75337667/cb55e439-805f-42ea-8a06-2c506e6b3cf8)

![Settings #2](https://github.com/cyanfish/naps2/assets/75337667/7cff56f7-087f-4159-ba67-ac434d036599)

![Settings #2 Scan](https://github.com/cyanfish/naps2/assets/75337667/8f46bba5-e890-4df2-84fb-f1d4d7c81400)

**Comment by jahvari** [comment]
Sorry, did not mean to close this issue. Attached are screenshots using TWAIN driver vs WIA in 7.1.2.

![Twain Scan Settings](https://github.com/cyanfish/naps2/assets/75337667/fe7db1f0-6f74-4bd1-9975-6445ecff6e89)

![Twain Scan](https://github.com/cyanfish/naps2/assets/75337667/b660ff7a-199e-449a-9b38-6d7d2350c338)

Issue seems to be with the WIA driver and fixed when using TWAIN driver.

**Comment by jahvari** [comment]
Sorry, did not mean to close this issue. Attached are screenshots using TWAIN driver vs WIA in 7.1.2. 

![Twain Scan Settings](https://github.com/cyanfish/naps2/assets/75337667/c4ffd7c3-ccb1-4872-adf4-e58dc592cb8a)

![Twain Scan](https://github.com/cyanfish/naps2/assets/75337667/f239c857-e0ca-4fde-aebf-6847183c4beb)

Issue seems to be with the WIA driver and fixed when using TWAIN driver.

**Comment by cyanfish** [comment]
What scanner model? Can you confirm that it's different between version 6.1.2 (or whatever prior version) and 7.1.2?

**Comment by jahvari** [comment]
The scanner model is: Kodak S2085f

I have confirmed that behavior is present in previous versions (I used v6.1.2). The issue seems to be related when using the WIA driver and having the "Use Predefined settings" button. 

I tested the WIA driver and "Use Native UI" with both v 7.1.2 and v6.1.2 and it cropped correctly.

**Comment by cyanfish** [comment]
Okay, to fix this would require supporting "Automatic" page size, which has been on the todo list for a while. I've created #226 to track it.
