### ISSUE TITLE
Dark mode causing havoc on some parts of NAPS2

### ISSUE THREAD

**Issue by clorophilla** [cyanfish/naps2#221]
I'm using Mint 21.1 with Dark theme enabled. (Mint-Y-Dark) When I try downloading OCR packages, I can't read anything on the window.

Here's a screenshot:
![image](https://github.com/cyanfish/naps2/assets/18373653/844fcce9-1ec1-47c3-a433-7dc98eb6effa)

**Comment by cyanfish** [comment]
What version of NAPS2 are you using?
