### ISSUE TITLE
New order option: Reverse Alternative Interleaved (scanned page order 5, 3, 1, 2, 4, 6)

### ISSUE THREAD

**Issue by AnaMarkH** [cyanfish/naps2#223]
**Is your feature request related to a problem? Please describe.**
Whenever a sequence of double-sided pages is accumulated over time (e.g. monthly payslips), in practice you open the folder and put the most current page on top of the stack of the older payslips. This results in a set of double-sided pages ordered by reverse date.

Currently, there is no order option for scanning such a set of interleaved pages. The available "altinterleave" option reorders the scans of a set of double-sided pages with page 1 being the **topmost** (i.e. it reorders pages from 135642 to 123456). But in the case described above, page 1 is the second page from the bottom of the stack.

**Describe the solution you'd like**
Introduce a "reverse alternative interleaved" option to reorder scanned pages from 531246 to 123456.

**Describe alternatives you've considered**
I did a quick&dirty mod on NAPS2 v6 to implement that option for the NAPS2 command line tool.

However, sources have changed dramatically in the current master, and I am not a "Pro" at all, so please apologize that I don't dare to make a fool of myself when trying to upload such a hack as suggestion to the git repo. ;-)

I **assume** that to make my suggested order option work in the current code of the command line tool, the changes to apply would be:

### naps2/NAPS2.Lib/Automation/AutomatedScanningOptions.cs (lines 61ff.)
```
    [Option("altinterleave", HelpText = "Alternate Interleave pages before saving.")]
    public bool AltInterleave { get; set; }

// BEGIN of added part
    [Option("revaltinterleave", HelpText = "Reverse Alternate Interleave pages before saving (531246 -> 123456).")]
    public bool RevAltInterleave { get; set; }
// END of added part

    [Option("deinterleave", HelpText = "Deinterleave pages before saving.")]
    public bool Deinterleave { get; set; }
```

### naps2/NAPS2.Lib/Automation/AutomatedScanning.cs (lines 225ff.)
```
            else if (_options.Deinterleave)
            {
                imageList.Mutate(new ImageListMutation.Deinterleave());
            }
// BEGIN of added part
            else if (_options.RevAltInterleave)
            {
                imageList.Mutate(new ImageListMutation.RevAltInterleave());
            }
// END of added part
            else if (_options.AltInterleave)
            {
                imageList.Mutate(new ImageListMutation.AltInterleave());
            }
```

### naps2/NAPS2.Lib/Util/ListMutation.cs (To be added below `public class AltInterleave : ListMutation<T> { ... }`)
```
    public class RevAltInterleave : ListMutation<T>
    {
        public override void Apply(List<T> list, ref ListSelection<T> selection)
        {
            // Partition the list in two
            int count = list.Count;
            int split = (count + 1) / 2;
            var p1 = list.Take(split).ToList();
            var p2 = list.Skip(split).ToList();

            // Rebuild the list, taking alternating items from each the partitions (the first in reverse order)
            list.Clear();
            for (int i = 0; i < count; ++i)
            {
                list.Add(i % 2 == 0 ? p1[(count - 1 - i) / 2] : p2[i / 2]);
            }

            selection = ListSelection.Empty<T>();
        }
    }

```

**Comment by cyanfish** [comment]
Tracking "Manual Duplex" rework in #303
