### ISSUE TITLE
Colour Scheme after Saving PDF on bottom right unreadable

### ISSUE THREAD

**Issue by jcurl** [cyanfish/naps2#225]
**Describe the bug**
Version 7.1.2

A UI bug. On windows 11, in the "dark mode" theme, save a PDF to the file system. On the bottom right there is a pop up describing the fie is saved, and to click where to save the file. Unfortunately, under the dark theme, this is unreadable.

![image](https://github.com/cyanfish/naps2/assets/1563519/7dfe8e10-7c60-49e7-b9ed-2877ff2774d3)

**To Reproduce**
1. Save a PDF file to disk.

**Expected behavior**
Text and the background should follow guidelines on contrast and readability.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2

**Comment by cyanfish** [comment]
This should be fixed in [7.2.0](https://www.naps2.com/download).
