### ISSUE TITLE
Graphics Bug when saving PDF in MacOS Sonoma

### ISSUE THREAD

**Issue by RonMcKay** [cyanfish/naps2#227]
**Describe the bug**
When saving a PDF, either all pages or only the selected ones, the page overview produces a strange graphics bug (see screenshot). The line on the bottom right and the area around it is clickable and opens some of the pages in the extra window when clicked.

**To Reproduce**
1. Scan some pages
2. Save the pages (CMD+S or CMD+Shift+S when pages are selected)

**Expected behavior**
PDFs should be saved and NAPS should display the overview of pages as usual.

**Screenshots**
![SCR-20231119-kryf](https://github.com/cyanfish/naps2/assets/36410367/a56e747e-604d-4c6a-b0e1-802184b6baae)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.1.1 (Sonoma)

**Additional context**
Not sure if that is relevant to the bug but I configured a standard PDF saving folder with some placeholders `scan_$(YYYY)$(MM)$(DD)_$(hh)$(mm)$(ss).pdf`.

**Comment by cyanfish** [comment]
This should be fixed in [7.2.0](https://www.naps2.com/download).
