### ISSUE TITLE
Some keyboard shortcuts in macOS Sonoma not working

### ISSUE THREAD

**Issue by RonMcKay** [cyanfish/naps2#228]
**Describe the bug**
Many keyboard shortcuts are not working any more and just produce an 'error' sound.

**To Reproduce**
Steps to reproduce the behavior (some examples):
- `Fn+Backspace` (aka `Del`) (should delete the selected pages)
- When opening a page by double clicking, the resulting window is not closable via `CMD+W`
- Go to the PDF settings page, type something in the standard path textbox, select it and try to copy it with `CMD+C`

All the above mentioned only produce the mac 'error' sound. At least the `Fn+Backspace` was working under macOS Ventura. About the rest I am not entirely sure if they also worked previously.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.1.1 Sonoma

**Comment by cyanfish** [comment]
This should be fixed in [NAPS2 7.4.1](https://www.naps2.com/download).
