### ISSUE TITLE
MAPI failure cases

### ISSUE THREAD

**Issue by cyanfish** [cyanfish/naps2#231]
https://sourceforge.net/p/naps2/tickets/1057/

**Comment by DestructiveSilence** [comment]
I have encountered the same _MAPI: Failure_ problem since NAPS2 6+.
Works correctly on version 5.8.2 and earlier.
MS Office 2010 - 2016. Windows 7 - 10.
I can run some tests if necessary.

**Comment by cyanfish** [comment]
This should be fixed in [NAPS2 7.3.0](https://www.naps2.com/download).
