### ISSUE TITLE
Improve OCR text alignment

### ISSUE THREAD

**Issue by cyanfish** [cyanfish/naps2#236]
Sometimes can be imprecise, e.g. https://sourceforge.net/p/naps2/tickets/1066/

One idea: Try and align on lines instead of words.

**Comment by Tarek-Hasan** [comment]
Hi,
Regarding OCR related issues, you should check out [OCRmyPDF](https://github.com/ocrmypdf/OCRmyPDF). This tool is build upon Tesseract and specialized to ease PDF OCR. It also doesn't change the resolution of the embedded images like other PDF OCR tools. Only caveat, the tool is in python.

**Comment by Tarek-Hasan** [comment]
Off-topic:
For your information, Empria software, the original developer of PDFsharp has released v6.x for .NET 6. It can be found [here](https://github.com/empira/PDFsharp).

**Comment by Tarek-Hasan** [comment]
You should try out OCRmyPDF to see if it solves your OCR related complications.
