### ISSUE TITLE
NAPS2 crashes when trying to use integrated print function

### ISSUE THREAD

**Issue by Nudelsalad** [cyanfish/naps2#238]
**Describe the bug**
When trying to print inside naps2 the program crashes

**To Reproduce**
1. Open Naps2 and scan or drop a pdf file that you want to print 
2. Click on print button in menu tabs
3. Naps2 crashes 

**Expected behavior**
I would expect to open a print dialog

**Screenshots**
The debug log shows no debugging information about the crash, the errorlog.txt reports:
`2023-11-23 08:07:57.8215 7480 Error stopping worker `

Terminal output of the crash:
```
(naps2:10148): Gdk-ERROR **: 08:18:26.715: The program 'naps2' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 12350 error_code 9 request_code 130 (MIT-SHM) minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Aborted (core dumped)
```

when naps2 freezes instead of closing immediatly after the crash or with verbose output enabled, I receive in Terminal:
`GLib-CRITICAL **: 08:19:40.643: g_hash_table_foreach: assertion 'version == hash_table->version' failed`

**Desktop (please complete the following information):**
 - OS: POP!OS 22.04LTS Gnome Desktop

**Comment by cyanfish** [comment]
This should be fixed in [7.2.0](https://www.naps2.com/download).
