### ISSUE TITLE
Japanese text does not OCR properly

### ISSUE THREAD

**Issue by Pawlicker** [cyanfish/naps2#246]
**Describe the bug**
Japanese language text will not OCR properly. 

**To Reproduce**

1. Try to OCR scanned Japanese text
2. Select text in PDF reader and copy it
3. The OCR'd text is a single character.

**Expected behavior**
Properly OCR'd text

**Screenshots**
Actual PDF file
[scan test 1.pdf](https://github.com/cyanfish/naps2/files/13540950/scan.test.1.pdf)

![image](https://github.com/cyanfish/naps2/assets/92184373/4922382b-bb8d-4146-b6e8-28d93874ba60)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - NAPS2 7.1.2.0
 
**Additional context**
This bug has been happening for a while, but I decided to finally report it. It OCRs properly when uploaded elsewhere such as archive.org.

**Comment by cyanfish** [comment]
This should be fixed in [7.3.1](https://www.naps2.com/download).
