### ISSUE TITLE
mac mini m2 pro with osx 14.2 -- the page size is not working

### ISSUE THREAD

**Issue by cvraosan** [cyanfish/naps2#249]
In mac mini m2 pro with OSX 14.1.2 -- the page size is not working

what ever size you select it scans image to a4 size only

i checked the latest version 7.2 and 7.1 

This issue started just now

Selected us legal paper size but it scans only a4 size

**Comment by cyanfish** [comment]
What scanner model? Are you using "Apple Driver" in your profile settings? Is the scanner connected by USB or over the network?

**Comment by cvraosan** [comment]
HiUsing HP 7740Connected over ethernet It was working nicely Even now a4 scanning is ok all the other features are working But paper size change does nit work It always scans at a4 sizeSent from 📱On 15-Dec-2023, at 3:25 AM, Ben Olden-Cooligan ***@***.***> wrote:﻿
What scanner model? Are you using "Apple Driver" in your profile settings? Is the scanner connected by USB or over the network?

**Comment by cvraosan** [comment]
Yes and apple driver selectedSent from 📱On 15-Dec-2023, at 6:26 AM, c venkateswara rao ***@***.***> wrote:﻿HiUsing HP 7740Connected over ethernet It was working nicely Even now a4 scanning is ok all the other features are working But paper size change does nit work It always scans at a4 sizeSent from 📱On 15-Dec-2023, at 3:25 AM, Ben Olden-Cooligan ***@***.***> wrote:﻿
What scanner model? Are you using "Apple Driver" in your profile settings? Is the scanner connected by USB or over the network?

**Comment by cvraosan** [comment]
HiAnd another thing is now i have a vpnExpress vpn which is turned onI did not try to test with it turned offWill do that and report back to youSent from 📱On 15-Dec-2023, at 6:27 AM, c venkateswara rao ***@***.***> wrote:﻿Yes and apple driver selectedSent from 📱On 15-Dec-2023, at 6:26 AM, c venkateswara rao ***@***.***> wrote:﻿HiUsing HP 7740Connected over ethernet It was working nicely Even now a4 scanning is ok all the other features are working But paper size change does nit work It always scans at a4 sizeSent from 📱On 15-Dec-2023, at 3:25 AM, Ben Olden-Cooligan ***@***.***> wrote:﻿
What scanner model? Are you using "Apple Driver" in your profile settings? Is the scanner connected by USB or over the network?

**Comment by cyanfish** [comment]
A couple things to try:
1. Can you change the page size if you use the built-in [macOS scanning](https://support.apple.com/en-ca/guide/mac-help/mh28032/mac)?
2. Does it work if you select "ESCL Driver" in your NAPS2 profile settings?

**Comment by cvraosan** [comment]
HiYes i tried with builtin apple scanning solution and it works perfectly for all types of page sizesESCL does not work in your programRgdsSent from 📱On 15-Dec-2023, at 9:49 AM, Ben Olden-Cooligan ***@***.***> wrote:﻿
A couple things to try:

Can you change the page size if you use the built-in macOS scanning?
Does it work if you select "ESCL Driver" in your NAPS2 profile settings?

**Comment by cvraosan** [comment]
Hi
Please find attached the setup screens of the NAPS2 on my Mac mini m2 pro

￼￼￼


Please see the full scanned image got from scanning using the MAC Scanning builtin software 
￼

**Comment by cvraosan** [comment]
hi

I downgraded to 7.09b-mac-univ.pkg 
and tried  here is the error
￼
￼

**Comment by UnciaPrima** [comment]
Hello,

I'm new to SNAPS2 but i think i'm experiencing the same problem (or a very similar one). I'm trying to scan A4 pages.
- Setting to greyscale generates a very weird image, very tilted and wrongly cropped. 
- Setting to Color scale generates a normal PDF file.

Scanning with Apple's Image Capture is perfectly normal.

Brother ADS-1200 / Macbook Air 2013 / macOS 11.7.3

**Comment by cyanfish** [comment]
The grayscale issue should be fixed in [NAPS2 7.2.1](https://www.naps2.com/download). I've also made a change that could help with page size but I'm not sure.

Please:
1. Try and see if page size works in 7.2.1 with Apple Driver.
2. If not, try again with ESCL Driver. If that doesn't work, please let me know what error you get etc. (p.s. I can't see images you send in email attachments, you'll have to reply on Github if you want to upload images)

**Comment by cvraosan** [comment]
Hi Ben
the bug is fixed -- now working well in 7.2.1

**Comment by cvraosan** [comment]
closed working well -- very good program and fast response from developer

**Comment by cvraosan** [comment]
closed working well -- very good program and fast response from developer

**Comment by UnciaPrima** [comment]
> The grayscale issue should be fixed in [NAPS2 7.2.1](https://www.naps2.com/download). I've also made a change that could help with page size but I'm not sure.
> 
> Please:
> 
>     1. Try and see if page size works in 7.2.1 with Apple Driver.
> 
>     2. If not, try again with ESCL Driver. If that doesn't work, please let me know what error you get etc. (p.s. I can't see images you send in email attachments, you'll have to reply on Github if you want to upload images)

Thank you very much for your quick answer and fix! I will be using NAPS2 from now!
