### ISSUE TITLE
[i18n] Certain string translated in .po files but not in .resx files

### ISSUE THREAD

**Issue by Matthaiks** [cyanfish/naps2#250]
**Describe the bug**
The `Shared scanners can be used from other computers on the local network by selecting "ESCL Driver" in the other computer's NAPS2 profile settings.` string displays always in English because it has been translated in .po files only (https://github.com/cyanfish/naps2/commit/b737ceba4f7631354a00599af2fd8f7e445468cb). 

**To Reproduce**
1. Switch to Czech, Italian, Hungarian or Polish
2. Go to Scanner Sharing
3. See the string in English

**Expected behavior**
The string should be translated.

**Screenshots**
![Window (2023 12 17, 08-31-48)](https://github.com/cyanfish/naps2/assets/3577122/ffe59528-c4b6-4397-91f8-267a099ffdae)

**Desktop (please complete the following information):**
 - OS:  Windows 10 22H2
 - Version: 7.2.1

**Comment by Matthaiks** [comment]
Fixed in 7.2,2. Thanks!

**Comment by isaak654** [comment]
> Fixed in 7.2,2. Thanks!

Not really, just switch to the Czech or Italian language:
![NAPS2_7 2 2](https://github.com/cyanfish/naps2/assets/12372772/9ef81c54-6a80-47b4-9b7c-e02e831af183)
