### ISSUE TITLE
Rotation option from CLI

### ISSUE THREAD

**Issue by bubizar** [cyanfish/naps2#252]
Bravo for this wonderful app. 🙌

It would be great to be able to chose **a rotation angle right from the CLI or as an option in profile**.
The goal is to rotate pages so OCR can work even on landcape documents. (all scanners are not able to auto-rotate scanned docs)

Many thanks.

**Comment by olfolfolf** [comment]
Indeed, that would be great!

**Comment by cyanfish** [comment]
I've added a [--rotate](https://www.naps2.com/doc/command-line#postprocessing-options) option in [NAPS2 7.3.0](https://www.naps2.com/download) (along with a [few more](https://github.com/cyanfish/naps2/releases/tag/v7.3.0)).
