### ISSUE TITLE
Range of IP addresses for eSCL driver.

### ISSUE THREAD

**Issue by DestructiveSilence** [cyanfish/naps2#254]
Could you add the ability to specify a range of IP addresses to search for devices via the eSCL driver?

Right now it only displays devices located on the same subnet as the computer (for me it is 10.12.**69**.xx). 
But beyond that, we have many MFPs in other ranges (like 10.12.**60**.xx, 10.12.**64**.xx, and so on).

**Comment by DestructiveSilence** [comment]
![MFPs](https://github.com/cyanfish/naps2/assets/38012433/caf60053-96ac-405b-acbb-6fd62c6726fa)
![Naps2](https://github.com/cyanfish/naps2/assets/38012433/ad6fc1b6-3b02-4646-ae32-bc4bb011b574)

**Comment by cyanfish** [comment]
ESCL uses mDNS for service discovery, which involves both NAPS2 and the scanners sending multicast packets to UDP 224.0.0.251:5353 (which get delivered to everything on the network).

If it's not finding the scanners, that means these packets aren't getting delivered across the subnet boundary. It should in theory be possible to configure the router between subnets to forward the packets, but how to do that depends on the hardware.

**Comment by cyanfish** [comment]
It's not an enterprise environment, but an example: https://blog.christophersmart.com/2020/03/30/resolving-mdns-across-vlans-with-avahi-on-openwrt/

You might also look for the term "Bonjour Gateway" in relation to whatever networking hardware you have.

**Comment by cyanfish** [comment]
Tracking documentation updates in #302
