### ISSUE TITLE
"Edit" profile opens "Auto saving settings" and if cancelled it deactivates the option

### ISSUE THREAD

**Issue by githubuser181226** [cyanfish/naps2#260]
Hi. Firstly, thank you for this wonderful program.

I've just upgraded to latest version (7.2.1.0) and now encounter this crippling bug when editting profiles.

**To Reproduce**
1. Create a profile, activate "Auto save settings". Save profile.
2. Open the profile for editting.
3. "Auto save setttings" is shown for whatever reason.
4. Click cancel (you've already set it up in step 1, and don't want to change). 
5. "Auto save settings" gets DEACTIVATED.

**Expected behavior**
As was before.
1. Editting profile should open profile editting form NOT auto save settings.
2. Auto save settings should NOT be deactivated if you click edit profile NOR when you cancel changing auto save settings if you set it up before already.

I haven't tested if the auto save settings are even saved in the 

Program is unusable like that. Please fix this ASAP.
Thank you.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 7.2.1.0.

**Comment by cyanfish** [comment]
Thanks, this should be fixed in [7.2.2](https://www.naps2.com/download).
