### ISSUE TITLE
Support HighDPI in Windows

### ISSUE THREAD

**Issue by arnowelzel** [cyanfish/naps2#263]
**Is your feature request related to a problem? Please describe.**
It seems, the Windows version is not DPI aware and when using it with scaling on a 4K display, the UI does not look very nice.

**Describe the solution you'd like**
It would be nice if the application had DPI awareness enabled and if needed using icons and bitmap rendering with upscaling to keep the original size.

**Describe alternatives you've considered**
I tried to enable advanced system upscaling in the application properties in Windows, but this did not help.

**Additional context**
See the screenshot here - this demonstrates the issue. The title bar is in rendered at the native resolution while the application content is blurred as it is only upscaled due to the missing DPI awareness:

![image](https://github.com/cyanfish/naps2/assets/6613614/92f2e363-cdfc-4741-a7ad-68d72d749bf5)

Another example - the profile edit dialog:

![image](https://github.com/cyanfish/naps2/assets/6613614/abcccebb-09be-4e68-8b69-56af8daad0c8)

**Comment by arnowelzel** [comment]
I started adding an `app.manifest` file to the application with the respective settings and use the need initialization. So getting DPI awareness is quite simple. However there is still work to do to handle the stored Window size as DPI independent value and to handle toolbar icons and bitmaps as device independent images which upscale if needed. Also the dialog element sizes may need to be adjusted depending on the display scaling:

![image](https://github.com/cyanfish/naps2/assets/6613614/5a1cb8b9-22a5-4e81-886f-085d16fc0c98)

However text and native Windows Forms controls in dialog windows already look much nicer this way:

![image](https://github.com/cyanfish/naps2/assets/6613614/9de68132-07a9-41f8-8370-7b2ce8c2147a)

**Comment by cyanfish** [comment]
#182 is a previous issue for this. My current plan is to do this after #81 which I think will make addressing element sizes easier.
