### ISSUE TITLE
Images in preview sometimes "disappears" when zooming

### ISSUE THREAD

**Issue by ShapeShifter499** [cyanfish/naps2#269]
**Describe the bug**
After scanning, images can "disappear" when trying to zoom in or out. But if you then resize the window, those same images come back in view. 

**To Reproduce**
1. Complete a new scan.
2. Attempt to zoom using the plus and minus magnifying glass icons in the bottom left corner a few times.
3. Observe that the preview area appears blank after zooming in or out a few times.

**Expected behavior**
The scanned images stay in preview no matter how many times you zoom in or out unless you actually delete or save the images.

**Desktop (please complete the following information):**
 - OS: Arch Linux, Linux 6.6.6-arch1-1-surface
 - Version: 7.2.2.0

**Comment by cyanfish** [comment]
Can you try with [NAPS2 7.4.1](https://www.naps2.com/download) and see if you still have the problem? Also, what desktop environment are you using?
