### ISSUE TITLE
OCR not done when saving image as PDF 

### ISSUE THREAD

**Issue by Lehnemann** [cyanfish/naps2#270]
**Describe the bug**
It happens when I try to save a image scan in PDF with OCR set, in Zorin OS 17 (linux OS with normal user). This is the error:

System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/usr/lib/naps2/_linux/tesseract' with working directory '/home/oninovadores/Documents'. Permission denied...

**To Reproduce**
1. After a successful scan, I tried to save as PDF by pressing the "Save PDF"s button.
2. Another window shows up with the above error. 
3. When I press the OK button, the PDF is saved without OCR been made.

**Expected behavior**
I was expecting a saved PDF file with text recognized.

**Desktop (please complete the following information):**
 - OS: Zorin OS 17, based on Ubuntu 22.04, with Gnome 45 and Wayland.
 - Version: 7.2.2.0.

**Additional context**
I found the solution in the comments [here](https://aur.archlinux.org/packages/naps2-bin). But...

**Comment by cyanfish** [comment]
This should be fixed in [NAPS2 7.3.0](https://www.naps2.com/download).
