### ISSUE TITLE
NAPS2 service mode

### ISSUE THREAD

**Issue by funkerwolf** [cyanfish/naps2#279]
Good evening, is there any consideration of adding a service mode for NAPS2 so that it can be scanned over the network without having to run it manually under a user account? I would also like the installer to display shortcuts to the desktop by default when distributing via GPO.

P.S. Thank you very much for implementing network scanning, you have solved a very big problem for many people that they don't even fully realize yet. And with your help I didn't have to suffer with such a pile of garbage as BlindScanner and other horrors.

**Comment by cyanfish** [comment]
Yes, this is definitely planned, see https://github.com/cyanfish/naps2/issues/253

As far as shortcuts, it should be possible to [add a shortcut](https://www.windows-active-directory.com/desktop-shortcuts-using-ad-group-policy-the-complete-guide.html) using GPO.

Glad you're liking the new feature :)
