### ISSUE TITLE
"About" window appearing when pressing F1 though not assigned in appsettings.xml

### ISSUE THREAD

**Issue by chyron8472** [cyanfish/naps2#280]
**Describe the bug**
After reassigning F1 to a `<ScanProfile>` and NOT to`<About>`, About window still appears when pressing F1 unless a Scan Profile is otherwise called.

**To Reproduce**
1. Set `<About>Ctrl+F1</About>` in appsettings.xml (or as any other hotkey, or leave it blank.)
2. Set `<ScanProfile1>F1</ScanProfile1>` in appsettings.xml
3. Open NAPS2.
4. Press F1. 
4a. BUG: Observe "About" window open
5. Click Scan dropdown
6.  While dropdown is open, press F1.
6a. Observe Scan Profile 1 being called.

-- Note: Scan Profile 1 does list F1 as its hotkey in the Scan dropdown menu.
-- If Scan dropdown menu is clicked and then closed, F1 still calls About window.
-- If Scan dropdown menu is clicked and F1 is pressed while menu remains visible, _then_ F1 correctly calls Scan Profile 1 and not About window.
-- If scan is attempted (by means other than pressing F1), pressing F1 afterward correctly calls Scan Profile 1 and not About window.

**Expected behavior**
Setting `<ScanProfile1>F1</ScanProfile1>` and `<About>Ctrl+F1</About>` in appsettings.xml should **always** call Scan Profile 1 when F1 is pressed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 7.3.0.0 Portable

**Comment by psp-oscar** [comment]
Possible another related issue, the main menu/ribbon items "About" & "Settings" disappeared from Version 7.3.0.0 (7.2.2.0 was ok) in case naps2 interface is set to any(?) language except English. 
OS: xUbuntu 18.04 & 22.04 deb.

**Comment by cyanfish** [comment]
@psp-oscar Feel free to create another issue, but you should be able to just make the window a bit wider for it to show up.

**Comment by cyanfish** [comment]
This should be fixed in [7.3.1](https://www.naps2.com/download).
