### ISSUE TITLE
Add list of keyboard shortcuts to the documentation

### ISSUE THREAD

**Issue by pelya** [cyanfish/naps2#286]
Could you please add a list of keyboard shortcuts to the documentation?
The app itself does not contain any help screen, so please add it to the website:

https://www.naps2.com/support

It is enough to list the default key bindings, but an instruction how to change them would be appreciated:

1. Close NAPS2 application
2. Copy `<KeyboardShortcuts>` section from the default config file, with all lines including the closing `</KeyboardShortcuts>` tag: https://github.com/cyanfish/naps2/blob/master/NAPS2.Setup/appsettings.xml#L85
3. Open NAPS2 config file with a text editor, on Linux it is located in `~/.config/naps2/config.xml`
4. Replace the empty `<KeyboardShortcuts />` section with the `<KeyboardShortcuts>` from the default config file
5. Edit individual shortcuts
6. Save the config file, launch NAPS2 application

**Comment by cyanfish** [comment]
I'm planning on adding keyboard shortcuts to the Settings window (see #61), so I'll do that instead of trying to document a complicated solution.

**Comment by pelya** [comment]
That would be even better

**Comment by muescha** [comment]
Is there a repository for the website where we can submit pull requests to add more information?

For example, I couldn’t find any details about config.xml in the support section of the website, but having that information would really help me modify the shortcuts.
