### ISSUE TITLE
failes to find scanner when internet blocked by firewall

### ISSUE THREAD

**Issue by TungstenE2** [cyanfish/naps2#294]
OS: Windows11
Version: 7.3.0.0

Click on Scan button.

Firewall detectes outgoing calls.

Connection to IP of scanner is allowed, all others blocked.

Autoupdate disabled.

Scanner not found when connection to internet is blocked.

Why is the app at all trying to make outbound calls?

![grafik](https://github.com/cyanfish/naps2/assets/39955685/00fc8b19-ce35-441c-97d2-4d2dd1c50ee5)

![grafik](https://github.com/cyanfish/naps2/assets/39955685/8820958b-13e7-4f83-86f7-e1f145425150)

![grafik](https://github.com/cyanfish/naps2/assets/39955685/d1757de1-df7e-41ec-a8ed-28ef6e80a207)

![grafik](https://github.com/cyanfish/naps2/assets/39955685/8cbc6ba9-1522-4643-a1b9-42069af62503)

**Comment by cyanfish** [comment]
If you're using the ESCL Driver, it uses mDNS to connect to the scanner, which requires sending packets to the multicast address 224.0.0.251:5353, which essentially asks the local network "what devices are on this network?". It doesn't involve any connection outside the local network.

See https://en.wikipedia.org/wiki/Multicast_DNS

**Comment by cyanfish** [comment]
Tracking documentation updates in #302
