### ISSUE TITLE
[Idea] Move language option to settings

### ISSUE THREAD

**Issue by Tarek-Hasan** [cyanfish/naps2#301]
As NASP2 now includes a settings window, move language option to there from main window.

**Comment by Tarek-Hasan** [comment]
Off-topic:
For your information, Empria software, the original developer of PDFsharp has released v6.x for .NET 6. It can be found [here](https://github.com/empira/PDFsharp).

**Comment by cyanfish** [comment]
I don't want to remove Language from the main toolbar by default, as if you're opening the app in the wrong language it's a lot easier to identify the globe icon than find something in menus. But per #207 I'm planning on letting users hide toolbar buttons they don't want, including the Language button.

I've had a quick look at PDFsharp 6.x. It looks like it has support for better encryption which is nice but not super important to me, and aside from that I don't think it can replace PdfSharpCore (e.g. it doesn't properly support macOS fonts, and it doesn't seem like they accept third-party PRs).

**Comment by Tarek-Hasan** [comment]
The cog icon is a universal symbol for settings/options. So I don't think finding the language option will be a problem for people who used a digital electronics in the last 30 years.

**Comment by cyanfish** [comment]
I've created #306 to track toolbar change suggestions.
