### ISSUE TITLE
Unable to unselect while images are being processed

### ISSUE THREAD

**Issue by josueetcom** [cyanfish/naps2#308]
**Describe the bug**

When I'm performing an operation on hundreds of images I'm unable to unselect anything and do anything else specific to one image.

**To Reproduce**
1. Import a large PDF with hundreds of pages
2. Select all the pages
3. Perform an Image operation such as Black and White.
4. Try unselecting and selecting or double clicking only one page.
5. Notice how the selection remains unchanged.

You have to wait until the image processing finishes but there is also no progress indicator anywhere. The best one I could figure out is the increase in memory usage in Activity Monitor. When it stops going up (are there memory leaks? The app crashed when I tried saving this PDF as I was writing this) that's when the image processing finishes and you can finally unselect and double click a page to view it.

**Expected behavior**

I expect to be able to select/deselect any image as I please. Otherwise I would expect a progress indicator so I can at least estimate when I'll be able to continue using the app.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.3 on an M1 16GB Macbook Air
 - Version: 7.3.1.0

**Additional context**

**Comment by cyanfish** [comment]
This should be fixed in [7.4.0](https://www.naps2.com/download).
