### ISSUE TITLE
Reorder scanned pages (manual duplex) and remove blank pages

### ISSUE THREAD

**Issue by thepoldy** [cyanfish/naps2#313]
My scanner doesn't support double-sided scanning, and I think a useful feature would be to enhance the alternating interleave (manual duplex) option with the option to remove blank pages. 

As of toay, both options (alternating interleave and removal of blank pages) co-exist. 
However, whenever a user does batch scanning of several documents, of which some have blank back-sides while other documents have printed back-sides, first the feature that removes the blanks kicks in and then the alternating interleave does not work anymore, as the blank back-sides have been removed already. 

Would be perfect to have an option to first re-order manual duplex (alternating interleave) and THEN remove any blank pages in a second step. 

Such a feature would enable the user to scan a pile of documents with manual duplex (where one- and double-sided documents may be scanned) and remove any blank back-sides. As a result, only printed pages in a correct order would make it into the final document. 

Such a feature / workflow would be very handy, in case of usage with QR-Codes & DMS-Systems, where the DMS system does split a batch-scanned pdf into seperate documents, whenever it dectecs a new QR code. 

Finally, thank you very much for maintaining this great project. By far the best scanning solution out there, that I am aware of.  :-)

**Comment by cyanfish** [comment]
Tracking this as part of #303 - it should be possible to internally store the page numbers of the pages scanned (before blank page removal) and use that as part of the re-ordering to account for blank pages.
