### ISSUE TITLE
Deskewed PDF file size is much bigger than normal

### ISSUE THREAD

**Issue by psaletan** [cyanfish/naps2#322]
**Describe the bug**
When "Deskew scanned pages" post-processing option is enabled in a scan profile, the file size of the scanned PDF is many times larger than when this option is disabled.

This problem occurs in release 7.3.1.0. For example, a black and white one-page scan at 300 dpi is 54 kb without deskew, but 732 kb with deskew enabled. In the 7.2.2 release, there is almost no difference between file sizes (54k vs 52k).

**To Reproduce**
1. Install naps2-7.2.2-linux-x64.deb on Debian 12.
2. Create a scanner profile for the Canon MX-470 scanner: SANE driver, Paper source = Glass, Bit depth = Black and white, Page size = US Letter, Resolution = 300 dpi. Ensure that "Deskew scanned pages" box ("Advanced" button) is NOT enabled.
3. Scan a single page on the flatbed.
4. Observe the file size.
5. Change the scanner profile by enabling "Deskew scanned pages".
6. Scan the same page again on the flatbed.
7. Observe that the file size is approximately the same as the non-deskewed scan.
8. Install/upgrade to naps2-7.3.1-linux-x64.deb on Debian 12.
9. Repeat steps 2-7.
10. Observe that the file size of the deskewed scan is much larger than the non-deskewed scan.

**Expected behavior**
The file sizes should be nearly the same (if the scan does not need much de-skewing).

**Screenshots**
![Screenshot_20240306_203034](https://github.com/cyanfish/naps2/assets/848139/bc7c9489-6fed-48d1-8414-4c1464742d5a)

**Desktop (please complete the following information):**
 - OS: Debian 12 ("Bookworm")
 - Version Kernel: Linux 6.1.0-16-amd64

**Additional context**
Upon request, I can upload sample PDF's demonstrating the problem.

**Comment by cyanfish** [comment]
This should be fixed in [7.4.0](https://www.naps2.com/download). (I don't think there's a difference between 7.2.2 and 7.3.1, it would just be related to whether the deskewing actually ended up detecting a rotation).
