### ISSUE TITLE
Include an `.RPM` package signature.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [cyanfish/naps2#335]
1.	#### **Is your feature request related to a problem? Please describe.**

	Although https://github.com/cyanfish/naps2/releases/download/v7.4.0/naps2-7.4.0-linux-arm64.rpm is installable on `cpe:/o:opensuse:tumbleweed:20240320` via https://en.opensuse.org/YaST_Software_Management#Installing_software

	> ![%Y%M%DT%H%m%S%t-24](https://github.com/cyanfish/naps2/assets/42837531/941732f1-b036-4b78-a234-35f8c7e6a0c2)

	and https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/zypper-1.14.68-1.4.x86_64.rpm, it isn't installable via https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/discover6-6.0.2-2.1.x86_64.rpm, and produces an error on the previously mentioned 2

	> ![%Y%M%DT%H%m%S%t-23](https://github.com/cyanfish/naps2/assets/42837531/9439b54c-8f28-4727-a5cc-4f90a254f8f4)

	due to its lack of https://github.com/redhat-developer/rpm-packaging-guide/blob/1f7a4bc61adfc415ba365c8c43a6b41d555ba328/source/advanced-topics.adoc#adding-a-signature-to-a-package.

1.	#### **Describe the solution you'd like**

	Add a package signature.

1.	#### **Describe alternatives you've considered**

	https://github.com/cyanfish/naps2/releases/download/v7.4.0/naps2-7.4.0-linux-arm64.flatpak

**Comment by cyanfish** [comment]
This should be done in [NAPS2 7.4.1](https://www.naps2.com/download). You can get the NAPS2 GPG key [here](https://www.naps2.com/naps2-public.pgp) (or from the download page).
