### ISSUE TITLE
Saving never completes

### ISSUE THREAD

**Issue by Dialga** [cyanfish/naps2#345]
**Describe the bug**
Saving file never completes

**To Reproduce**
1. Scan 39 documents of various sizes, A4,A5,US Letter
2. Click on save pdf to save the last document
3. Click save pdf again and save with the same name and replace/overwrite.
4. Document is saved but the save pdf progress window continues to show progress

**Expected behavior**
Save pdf progress window to automatically close after saving as the document has been saved.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Version 7.4.0

**Additional context**

**Comment by cyanfish** [comment]
This should be fixed in [NAPS2 7.4.1](https://www.naps2.com/download).
