### ISSUE TITLE
Saving PDF as PDF/A-2b produces PDF 1.4 files instead of 1.7

### ISSUE THREAD

**Issue by NextTherapist** [cyanfish/naps2#348]
**Describe the bug**
Saving PDF with NAPS2 as PDF/A-2b produces PDF 1.4 files instead of 1.7. According the standard the PDF version for PDF/A-2b files is version 1.7, not 1.4.

**To Reproduce**
1. Scan or import a file
2. Save it as PDF with setting "PDF/A-2b"
3. Control the resulting version in PDF viewer.

**Expected behavior**
NAPS2 should produce a PDF 1.7 file in this case. Wikipedia says: 
"PDF/A-2 | Part 2: Use of ISO 32000-1 | 2011-06-20 | ISO 19005-2 | PDF 1.7 (ISO 32000-1:2008)"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 7.4.0 (and earlier)

**Comment by cyanfish** [comment]
This should be fixed in [NAPS2 7.4.1](https://www.naps2.com/download).
