### ISSUE TITLE
Vertical scanning of an envelope is turned to landscape and page too big

### ISSUE THREAD

**Issue by NextTherapist** [cyanfish/naps2#354]
**Describe the bug**
I scan an envelope with some printed words on it. NAPS2 rotates the scan and shows it with the words in the right direction to read.

BUT: I do not want the rotation, since the other scans for this PDF file are portrait and I want a consistent portrait PDF file.
(And I wonder how NAPS2 knows how to rotate since OCR isn't done at this moment. Perhaps it comes from the Canon Twain Driver, that's possible.)

And when I rotate the page manually back to portrait and save the PDF, the rotated page is not DIN A4 size like the others, but much bigger: 928 x 656 mm!

**Expected behavior**
If a rotation happens due to the Twain driver, it should be possible to rotate back in NAPS2 and preserving the wanted paper size.
Even better would be a setting to force portrait scans in NAPS2, not caring for the twain settings.

**Comment by cyanfish** [comment]
It sounds like the driver is doing the rotation and misrepresenting the page size. A fix (though not ideal) would be to create a custom page size with dimensions flipped for landscape, then check "stretch to page size" under Advanced in your profile settings to ensure the size is corrected.
