### ISSUE TITLE
Mouse Scroll Wheel with Ctrl pressed not working any more with 7.4.1

### ISSUE THREAD

**Issue by bmxp** [cyanfish/naps2#355]
**Describe the bug**
Display size of pages coule before increased or decreased with ``ctrl``+``Mousewheel``. That's not working any more

**To Reproduce**
Just try the above combination of Ctrl+Mousewheel

**Expected behavior**
Increase display size of pages as before

**Screenshots**
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 7.4.1

**Comment by RoPoXx** [comment]
This problem exists here too. In the previous version it works correctly.

**Comment by cyanfish** [comment]
This should be fixed in [7.4.2](https://www.naps2.com/download).
