### ISSUE TITLE
the examples from the article do not work

### ISSUE THREAD

**Issue by amber8706** [cyanfish/naps2#358]
The article describes non-existing commands.

https://www.naps2.com/doc/command-line

naps2.console output:
Option 'driver' is unknown.
Option 'listdevices' is unknown.

If I try to use command:
naps2.console --listdevices --driver twain

Have these commands changed? How do I display a list of devices? The examples are very convenient, but they don't work. Is this bug?

**Comment by cyanfish** [comment]
Are you using the latest version of NAPS2?
