### ISSUE TITLE
7.0b1 Scanning now opens extra windows, can hang

### ISSUE THREAD

**Issue by jcurl** [cyanfish/naps2#36]
**Describe the bug**
This appears to be a regression over v6.1.2. An extra window appears when using my TWAIN scanner (that did not appear before). It is visible with a short title bar only. Closing this window closes the scanner TWAIN interface and NAPS is no longer responsive. Must go to the task manager to close.

**To Reproduce**
1. Go to Scan -> Choose Scanner.
![image](https://user-images.githubusercontent.com/1563519/210216104-ce8ad1be-547c-4607-9abf-d98135b3c741.png)
2. The scanner now appears on the bottom right. Next to it is an empty window
![image](https://user-images.githubusercontent.com/1563519/210216234-40045813-f632-41b1-8f16-6b055024592b.png)
3. Closing that window and NAPS now hangs. Must use the Task Manager to close the NAPS windows. This can lead to loss of data.

The profile window for the scanner is:
![image](https://user-images.githubusercontent.com/1563519/210216354-02bcb9c1-b47e-4860-a921-92382117bae9.png)

![image](https://user-images.githubusercontent.com/1563519/210216464-cf92ae93-07f7-4d0a-ace5-acf9ba6a347b.png)

**Expected behavior**
Same behaviour as in NAPS 6.1.2

**Desktop (please complete the following information):**
 - Windows 10 19043.

**Additional context**
The same occurs for my OKI scanner also. It might be related to recent changes in TWAIN?

**Comment by cyanfish** [comment]
I'll try and fix the extra window later. But in 7.0b2 I put a change that might help with the hang - please try and let me know if it changes anything.

**Comment by jcurl** [comment]
Still problematic in NAPS 7.0b2.

**Comment by cyanfish** [comment]
Thanks, I think this should be fixed in [7.0b3](https://www.naps2.com/download). Please let me know if it works for you.
