### ISSUE TITLE
Supress question for Scanner, if only one defined

### ISSUE THREAD

**Issue by Moosbueffel** [cyanfish/naps2#365]
**Is your feature request related to a problem? Please describe.**
The problem is, that I need an additional click at every scan.

**Describe the solution you'd like**
If there is only one scanner defined (and in the choice menue), than supress the dialog to choose a scanner, because there is only one choice.

**Comment by cyanfish** [comment]
In your profile settings, choose a device and you won't need to pick one when you scan.

**Comment by Moosbueffel** [comment]
Thanks, that was the trick :).
