### ISSUE TITLE
 How to batch scan pdf-files to specified folders   by sdk

### ISSUE THREAD

**Issue by 800903** [cyanfish/naps2#376]
how to set one file per page 
ScanningContext scanningContext = new ScanningContext(new GdiImageContext());
            var scanController = new ScanController(scanningContext);
            var devices = await scanController.GetDeviceList(Driver.Wia);          
            var options = new ScanOptions
            {
                Device = devices.First(),
                PageSize = PageSize.A4,
                PaperSource = NAPS2.Scan.PaperSource.Flatbed,
                Dpi = 600
            };
            var images =await scanController.Scan(options).ToListAsync();
            var pdfExporter = new PdfExporter(scanningContext);
            await pdfExporter.Export("doc.pdf", images); ?????  ???????  specified dynamic  folders

**Comment by 800903** [comment]
I don't know if it will be effective.

 
 public async Task ScanWithTwain(string filepath)
        {
            
            ScanningContext scanningContext = new ScanningContext(new GdiImageContext());
            var scanController = new ScanController(scanningContext);
            var devices = await scanController.GetDeviceList(Driver.Wia);
            var options = new ScanOptions
            {
                Device = devices.First(),
                PageSize = PageSize.A4,
                PaperSource = NAPS2.Scan.PaperSource.Flatbed,
                Dpi = 600
            };           
            var images =await scanController.Scan(options).ToListAsync();
            var pdfExporter = new PdfExporter(scanningContext);
            string currentFileName = "";
            int pages= 0;
            var compat = PdfCompat.Default;
            PdfSettings pdfSettings = new PdfSettings();
            pdfSettings.Compat = compat;
            pdfSettings.SinglePagePdfs = true;
            pdfSettings.DefaultFileName = "0000.pdf";
            var imagesByFile = pdfSettings.SinglePagePdfs ? images.Select(x => new[] { x }).ToArray(): new[] { images.ToArray() };
            foreach (var imagesForFile in imagesByFile)
            {
                {
                    pages++;
                    currentFileName = filepath + pages.ToString("D4") + ".pdf";
                    await pdfExporter.Export(currentFileName, imagesForFile, new PdfExportParams(pdfSettings.Metadata, pdfSettings.Encryption, pdfSettings.Compat));
                }
            }
            
        }

**Comment by cyanfish** [comment]
First, I'd recommend updating to the latest SDK version, where PdfSettings isn't available because it doesn't do anything.

But as far as code, you don't need any special NAPS2 functionality, just a for loop:
```c#
int i = 1;
foreach (var image in images) {
    await pdfExporter.Export($"{i++:D4}.pdf", new[] { image });
}
```

**Comment by cyanfish** [comment]
Well, you'll need to put in a full file path depending on where you want to save it.

**Comment by 800903** [comment]
Here's the full code.
   public async Task ScanWithWia()
        {
            ScanningContext scanningContext = new ScanningContext(new GdiImageContext());
            var scanController = new ScanController(scanningContext);
            var devices = await scanController.GetDeviceList(Driver.Wia);
            var options = new ScanOptions
            {
                Device = devices.First(),
                PageSize = PageSize.A4,
                PaperSource = NAPS2.Scan.PaperSource.Flatbed,
                Dpi = 600
            };
            var images = await scanController.Scan(options).ToListAsync();
            var pdfExporter = new PdfExporter(scanningContext);
            int pages = 0;
            foreach (var image in images)
            {
                pages++;
                await pdfExporter.Export("D:\\" + pages.ToString("D4") + ".pdf", new[] { image });
            }
        }

**Comment by 800903** [comment]
<img width="1280" alt="微信图片_20240423184938" src="https://github.com/cyanfish/naps2/assets/166220011/840870f2-1ee9-437e-828e-70bf8b4e8687">

**Comment by 800903** [comment]
<img width="842" alt="20240423185514" src="https://github.com/cyanfish/naps2/assets/166220011/007dd684-aaaf-403a-ad75-187fc636564e">

**Comment by 800903** [comment]
<img width="617" alt="20240424185659" src="https://github.com/cyanfish/naps2/assets/166220011/64793d51-f3d0-4721-94c5-bdac7016df8b">
this is the value of images.  maybe is wrong

**Comment by 800903** [comment]
ScanningContext scanningContext = new ScanningContext(new GdiImageContext());
 // got it done  must be add  FileStorageManager  object, Otherwise, the pdf file cannot be saved
FileStorageManager fileStorageManager = new FileStorageManager(@"c:\temp");          
scanningContext.FileStorageManager = fileStorageManager;
//=======================================================
