### ISSUE TITLE
7.0b1 Regression, drag and drop of PDF no longer works

### ISSUE THREAD

**Issue by jcurl** [cyanfish/naps2#38]
**Describe the bug**
In NAPS 6.1.2 it was possible to drag and drop a PDF onto the main window, and it would be imported. With NAPS 7.0b1 it is no longer possible.

**To Reproduce**
1. Find a PDF document
2. Drag and drop it onto the Window from NAPS, it is empty (just started, no existing document).
3. The icon is marked that drag and drop is not possible, and releasing is no action.

**Expected behavior**
Drag and drop of the PDF should import the PDF.

**Screenshots**
No screenshot possible while drag and drop in progress.

**Desktop (please complete the following information):**
 - Windows 10.19043 64-bit

**Additional context**
None.

**Comment by bebobebo** [comment]
Can't drag and drop image files e.g. PNG to import either

**Comment by cyanfish** [comment]
Thanks, this should be fixed in [beta 2](https://www.naps2.com/download).

**Comment by jcurl** [comment]
Drag and drop now works, but not if there is a NON-ASCII char. e.g. if the file is called `foobär.pdf` it raises an exception. See https://github.com/cyanfish/naps2/issues/49
