### ISSUE TITLE
ESCL no longer working with v 7.4.2.0  - Windows 11

### ISSUE THREAD

**Issue by TungstenE2** [cyanfish/naps2#389]
ESCL no longer working with v 7.4.2.0  - Windows 11

Brother Scanner starts, but no pages are received by NAPS2.

Changed to TWAIN driver, this is working. ESCL was working fine before.

Please check

**Comment by rousseldenis** [comment]
I can say 7.4.2 is working fine on Win10

**Comment by ps1noob** [comment]
> ESCL no longer working with v 7.4.2.0 - Windows 11
> 
> Brother Scanner starts, but no pages are received by NAPS2.
> 
> Changed to TWAIN driver, this is working. ESCL was working fine before.
> 
> Please check

Can confirm, Brother Scanner, NAPS2 7.4.2.0 with ESCL driver on Windows 11, no pages were received by NAPS2 after the scan process. Using TWAIN it works as expected.

**Comment by cyanfish** [comment]
Please try this with [7.4.3](https://www.naps2.com/download).
