### ISSUE TITLE
Can the command line be used to cancel the scanning task?

### ISSUE THREAD

**Issue by hfbi360** [cyanfish/naps2#393]
**Is your feature request related to a problem? Please describe.**
When I used the command line to cancel the ongoing scan task, I did not find the relevant command

**Describe the solution you'd like**
Use the command line to gracefully interrupt an ongoing scan task

**Describe alternatives you've considered**
I considered killing the process that started the scan command, but found that when I started the scan again, I couldn't start the scanner.

**Comment by cyanfish** [comment]
This should be fixed in [7.5.2](https://www.naps2.com/download).

**Comment by cyanfish** [comment]
Specifically, Ctrl+C should work to gracefully interrupt the scan.
