### ISSUE TITLE
what is the point of asking constantly about using the same scanner?

### ISSUE THREAD

**Issue by f1-outsourcing** [cyanfish/naps2#405]
I have 1 scanner, so what is exactly the point of asking in a popup to choose it with every scan?

**Comment by cyanfish** [comment]
Go to your profile settings, edit your profile, and select a scanner in the profile. Then it won't ask again.

**Comment by f1-outsourcing** [comment]
Yes, thanks! Nice app, maybe make this default? 

Just ridiculous that I need to use it because shitty windows 10 scanning is not working (when your remove all the microsoft app store crap)
