### ISSUE TITLE
Horizontal align: left leads to wrong document size

### ISSUE THREAD

**Issue by NextTherapist** [cyanfish/naps2#407]
**To Reproduce**
Set your scanning profile to page size A4 (297x210 mm).
Set horizontal align to "left" (I thought this is normal for LTR languages)
Scan a document and you will get an image sized 297x204 mm! It is cut off on the left side. The error passes right through to the PDF file.

**Expected behavior**
A page size like I selected it: A4 (297x210 mm), like with Horizontal align: right

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 7.4.2

**Comment by cyanfish** [comment]
Right-alignment is the default. But if you do need left, in your profile settings, under Advanced, try checking "Offset width based on alignment".
