### ISSUE TITLE
Starting to scan via Twain takes nearly 10 seconds before the scanner starts

### ISSUE THREAD

**Issue by NextTherapist** [cyanfish/naps2#408]
**Describe the bug**
Starting to fetch a scan from a Canon Document Scanner takes nearly 10 seconds to wait before the scanner starts to pull in the paper.
I compare it with the standard Canon Software (CaptureOnTouch) which starts scanning immediately.

I tried out the existing twain options. All of them work, except the x64 version, but they all need these delay seconds before they start scanning.

**Expected behavior**
Pressing the scan button and hearing the scanner beginnig to work immediately.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 7.4.2

**Comment by cyanfish** [comment]
This sounds like an issue with the Canon TWAIN driver, there's not much I can do about that on the NAPS2 end.
