### ISSUE TITLE
No way to delete a scan settings profile

### ISSUE THREAD

**Issue by haebler** [cyanfish/naps2#409]
**Describe the bug**
When in the "New Scan" dialog, I can create a new profile for the scanner settings but I am unable to delete an existing profile or make it the default.
 
**To Reproduce**
1. Click "Scan"
2. Wait for dialog to open
3. no UI controls to delete a scan configuration profile or make a profile the default

**Expected behavior**
I can remove and modify scan profiles. There seems to be no other place in the UI these are exposed either.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11
 - Version 7.4.2.0

**Additional context**
NA

**Comment by cyanfish** [comment]
Click the "Profiles" button on the toolbar.

**Comment by haebler** [comment]
What I mean by scan profiles is this. I do not see a way to manage them, other than creating new ones:
![image](https://github.com/cyanfish/naps2/assets/565338/dba645ef-2991-4727-ace7-01d10bf720f6)

Profiles gets me to the scanner profile, not the scan profile: 
![image](https://github.com/cyanfish/naps2/assets/565338/837d036c-dcff-4586-967c-5b75aa6df577)

**Comment by cyanfish** [comment]
Those are Windows scanner profiles, not NAPS2. You can try something like this:
https://answers.microsoft.com/en-us/windows/forum/all/editing-windows-fax-scan-scan-profiles/72fac3e7-4bf0-401a-be22-321093ffea1f

Or select "Use predefined settings" instead of "Use native UI" to use NAPS2 profiles.

**Comment by haebler** [comment]
@cyanfish Thanks so much for clarifying that!!!! Will set up some NAPS2 profiles and try that.

For all, who are looking for those settings in Windows 11, IMHO the best option is to go through "Windows Scan & Fax"
![image](https://github.com/cyanfish/naps2/assets/565338/55d4964f-a9c5-43e4-9cfd-f67f05b76738)
