### ISSUE TITLE
Scanner Error - Unknown error. [Error Code=27]

### ISSUE THREAD

**Issue by Neo6400** [cyanfish/naps2#415]
Hello

I am trying to implement the scanning function in a 64 bits WPF app (NET 4.8), I have installed the library through NuGet.
I have a scanner Canon DR - S150 connected through Ethernet.
The scanning function works fine however I am getting the popup below twice every time I scan. 
After investigating the issue it seems the error is thrown by the 32 bits NAPS2.Worker.exe
My TWAIN drivers and the scanner firmware are up to date.

Any help would be greatly appreciated.

![img](https://github.com/user-attachments/assets/459d02fa-dd39-40bd-af27-7dc5a84257b9)

Thank you

**Comment by cyanfish** [comment]
Do you get the same error when scanning through the NAPS2 app? This is coming from the Canon driver so there's might not be much that can be done on the NAPS2 end.
