### ISSUE TITLE
NAPS2.Console.exe - Error "TWAIN error: MaxConnections" when scanning again after canceling the scanning process (Citrix)

### ISSUE THREAD

**Issue by rothtobi** [cyanfish/naps2#423]
**Describe the bug**
When using NAPS2.Console.exe within a Citrix session, we have the problem that the following error message appears during the next scan after clicking Cancel: "TWAIN error: MaxConnections"

**To Reproduce**
1. Start the Commandline: 
`NAPS2.Console.exe --output "C:\TEMP\test.jpg" --force --progress --device "PaperStream IP SP-1125 #2" --driver twain --noprofile`
2. Click on "Cancel" during scanning.
![image](https://github.com/user-attachments/assets/10039e76-7271-4916-852e-33d6b0842bb2)
The following appears in the console: "No scanned pages to export."
3. Start the Commandline again: 
`NAPS2.Console.exe --output "C:\TEMP\test.jpg" --force --progress --device "PaperStream IP SP-1125 #2" --driver twain --noprofile`
The following error message appears: 
TWAIN error: MaxConnections
No scanned pages to export.

**Expected behavior**
The next scan should work if the previous scan was canceled.

**Screenshots**
![image](https://github.com/user-attachments/assets/932529d1-71d9-4e88-b574-74819867170d)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Version 7.4.3

**Additional context**
- We could not reproduce the problem with the NAPS2.exe instead of the NAPS2.Console.exe, here the connections to the scanner seem to be terminated correctly when clicking on Cancel.
- In order for the scanner to work again, the entire Citrix session must be logged off and logged on again.
- The NAPS2.Console.exe always terminated normally and no NAPS2.*.exe remained hanging.

**Comment by cyanfish** [comment]
This should be fixed in [7.5.2](https://www.naps2.com/download).
