### ISSUE TITLE
Profile not visible in "Profiles" window after restarting NAPS2 when choosing TWAIN driver for device

### ISSUE THREAD

**Issue by Compunologist** [cyanfish/naps2#430]
**Describe the bug**
After creating a new profile for the device with the TWAIN driver the program works normally but after restarting NAPS2 the profile will no longer be visible. The debug/error log starts with the message "Error parsing config C:\Users\XXXXX\AppData\Roaming\NAPS2\profiles.xml"

**To Reproduce**
1. Start NAPS2
2. Click on "Profiles"-->"New"
3. Click "Choose device" in the "Profile Settings"
4. Select "TWAIN Driver" and the device
5. Adjust the "Profile Settings" to your liking
6. Click "OK"-->The newly created profile is now visible in the "Profiles" window. Close the "Profiles" window.
7. Exit NAPS2 and restart NAPS2
8. Click on "Profiles"-->The "Profiles" window is empty, the newly created profile is no longer visible

**Expected behavior**
The newly created profile should remain visible in the "Profiles" window after restarting NAPS2.

**Screenshots**
![Selecting TWAIN Driver and device](https://github.com/user-attachments/assets/4e1cf7f0-9288-4f5c-8541-55924691c1a7)
_Select TWAIN Driver and the device_

![Profile settings](https://github.com/user-attachments/assets/b562da8c-e8f3-4796-a9cd-5e92d47ecfeb)
_Adjust profile settings to your preference_

![Profile visible](https://github.com/user-attachments/assets/f7885d0b-355f-492e-8785-01c86d7bcfa0)
_The newly created profile appears in the "Profiles" window_

![Profiles empty after restarting NAPS2](https://github.com/user-attachments/assets/283e0307-02be-4a8d-8318-dad2b2999377)
_The newly created profile is not visible after restarting NAPS2_

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro version 22H2, OpenSUSE Leap 15.6
 - Version 7.5.0.0

**Additional context**
The issue only occurs when the TWAIN driver is selected (Windows 10). When the WIA driver is selected, the profile will remain visible after restarting NAPS2. I also haven't been able to reproduce the issue on Linux OpenSUSE. The debug/error log starts with the message "Error parsing config C:\Users\XXXXX\AppData\Roaming\NAPS2\profiles.xml" 
[debuglog.txt](https://github.com/user-attachments/files/16605395/debuglog.txt)
[errorlog.txt](https://github.com/user-attachments/files/16605396/errorlog.txt)

**Comment by cyanfish** [comment]
Thanks for reporting this, it should be fixed in [7.5.1](https://www.naps2.com/download).
