### ISSUE TITLE
UI blurry for some reason 

### ISSUE THREAD

**Issue by Pavelmez** [cyanfish/naps2#431]
**Describe the bug**
UI seem to be blurry for no reason.

**To Reproduce**
it seem to be happened on my laptop I already tries re install and it still blurry but in my PC is normal

**Expected behavior**
the UI to be crisp

**Screenshots**
blurry UI and if there is a document in there it will be blurry as well 
![Screenshot 2024-08-14 153337](https://github.com/user-attachments/assets/8fc4f44c-3770-4d66-b0d2-51bb4f9d04e3)

**Additional context**
fix enable high dpi calling override

**Comment by cyanfish** [comment]
See #182
