### ISSUE TITLE
Save files to the destination folder while scanning

### ISSUE THREAD

**Issue by zwo1a** [cyanfish/naps2#433]
**Is your feature request related to a problem? Please describe.**
When scanning a large number of images, it is often necessary to wait a long time for the save action to complete.

**Describe the solution you'd like**
Provides an option to save image files to a destination folder while scanning to minimize wait time.
When the user makes changes to the image after scanning (after cropping, adjusting colors), the user is prompted to save again.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cyanfish** [comment]
Check "Auto Save" in your profile settings.

**Comment by zwo1a** [comment]
Sorry, I missed that option. This issue has been resolved.
