### ISSUE TITLE
Page Order Issue with High-Speed Scanning on EPSON DS-32000

### ISSUE THREAD

**Issue by doingso** [cyanfish/naps2#435]
Describe the bug
I'm a user of NAPS2 on macOS, and I encountered an issue while scanning with the EPSON DS-32000 model. Due to the high scanning speed of the DS-32000, a problem occurs under the following conditions:
a. When there are four pages (two sheets) in total,
b. The first sheet has a colorful image on the first page, and the second sheet is just a blank white page.

Under these conditions, I've noticed that the second page (the blank one) appears first in NAPS2, and the first page (with the image) appears afterward as the back page in NAPS2. I suspect this might be due to asynchronous image processing, but I'm not sure and would like some help in resolving this.

To Reproduce

Use macOS and NAPS2 with an EPSON DS-32000 scanner.
Scan a colorful image followed by a blank page.
Observe that the blank page appears first in NAPS2, followed by the image page as the back page.
Expected behavior
The scanned pages should appear in the correct order as they are fed into the scanner.

Screenshots
- If you need, I will capture tomorrow

Desktop (please complete the following information):

OS: macOS [14.2]
Version: NAPS2 [7.5.1]
Additional context

I'm not sure of the exact cause but suspect it might be related to asynchronous image processing. 
Any help or guidance would be appreciated.

**Comment by cyanfish** [comment]
This should be fixed in 7.5.2.
