### ISSUE TITLE
hide some parts of a document (e.g. confidential informations)

### ISSUE THREAD

**Issue by AlBundy33** [cyanfish/naps2#437]
**Is your feature request related to a problem? Please describe.**
After scanning or importing documents with confidential/private/non-public informations...

**Describe the solution you'd like**
... it would be nice to have an option to wipeout some parts of the documents e.g. with a black square, blurring, pixelation, ... or a combination of all.

**Describe alternatives you've considered**
The workaround is to edit the documents (pdf or image) in an external tool first.

**Additional context**
With this feature it would be possible to directly send (or store) PDFs without leaking to much informations.

**Comment by cyanfish** [comment]
Similar to #39
