### ISSUE TITLE
Cancel Save Action Ignored

### ISSUE THREAD

**Issue by JPluess** [cyanfish/naps2#438]
Issue: The system is set to autosave but still prompt for a filename check, like so:
![grafik](https://github.com/user-attachments/assets/cf2ce2e6-38a9-4c77-b605-7615b60ea0b5)
![grafik](https://github.com/user-attachments/assets/0f937736-265a-4f3b-bb3d-e5cb1a9bd7bd)

If a scan is performed it asks for filename but, if "Cancel" is pressed, it saves the file anyway.

Request: Ensure that if the user presses "Cancel," the save process for that file is ignored.

**Comment by cyanfish** [comment]
This should be fixed in [7.5.2](https://www.naps2.com/download).
