### ISSUE TITLE
Submit to webhook

### ISSUE THREAD

**Issue by 12nick12** [cyanfish/naps2#444]
**Is your feature request related to a problem? Please describe.**
Just like email option it would be nice to have an option to submit to webhook (this should include custom headers for webhooks that require auth)

**Describe the solution you'd like**
Just like email option it would be nice to have an option to submit to webhook (this should include custom headers for webhooks that require auth)

**Comment by cyanfish** [comment]
I'm going to group this with #106 which is a similar/more general concept
