### ISSUE TITLE
#support NAPS2 can't see Pantum BM5100ADW scanner in centos based linux system

### ISSUE THREAD

**Issue by accidentalZero** [cyanfish/naps2#445]
After installation of driver package. Printer pantum 5100 adw works just perfectly with printing and scanning through default scanner program. But in my organization people have been use NAPS2 for a long time. 

After migration from Windows to Linux we have issue with this MFP devices and NAPS2. What information can i provide to help develop programm in this case?

OS is ROSA linux, dirver stored in default repo

**Comment by cyanfish** [comment]
Are you connecting with USB or Wifi? Have you tried both SANE and ESCL driver options? If wifi, have you tried installing sane-airscan?
