### ISSUE TITLE
Persistent paper jam error after clearing jam

### ISSUE THREAD

**Issue by erflaber** [cyanfish/naps2#449]
**Describe the bug**
Error message persists after clearing a paper jam.

**To Reproduce**

1.     Induce a paper jam during scanning.
2.     Clear the paper jam.
3.     Continue scanning.
4.     Observe that the error message "paper jam" is displayed after each subsequent scan, despite the scan completing successfully and no paper jam being present.

**Expected behavior**
No error message should be displayed if there is no paper jam in the scanner.

**Screenshots**

![image](https://github.com/user-attachments/assets/e1f4576b-45c3-428e-a253-268832bd057f)

**Desktop (please complete the following information):**

- OS: Linux Mint 22 Cinnamon
- Version: 7.5.1.0

**Additional context**

- Device: HP OfficeJet Pro 9010 series [8B21C6]
- Driver: Sane Driver airscan
- Connection: Home Wi-Fi
- The error appear after each scan.
- Note: Using the SANE Driver with escl results in an error before scanning, preventing scanning altogether.

**Comment by erflaber** [comment]
Also to add: I am using the duplex.

**Comment by cyanfish** [comment]
Do you get a similar error with scanimage or sane?

**Comment by erflaber** [comment]
I just tried it with xsane and the settings in the screenshot.

![image](https://github.com/user-attachments/assets/958439af-1355-4e0e-9672-8a76a33fa229)

It give me the same paper jam error, but this time before the scan and once I clicked OK, it did scan without issues. With NAPS2 I am getting the error after the scan with the same driver. The other drivers give the error without scanning.

**Comment by erflaber** [comment]
That makes sense. Thank you for helping me figure it out.
