### ISSUE TITLE
Starting naps2 7.5.1.0 in full screen shows a smaller workplace

### ISSUE THREAD

**Issue by yoyoweb** [cyanfish/naps2#453]
**Describe the bug**
A the start of the nap2 application, on windows, the display is full screen (from the last session ended) what is expected but the workspace is smaller (not full screen).
I have to click on the button "display window" from windows (close to the X close button), and then click on  the full screen button. After that the display is as expected : the workspace is as big as the screen.
But when I close naps2, the problem appears again.

**To Reproduce**
1. Click to start to naps2 application
2. Display is in full screen, but workspace is smaller than the full screen. This behaviour is new since 7.5.1.0 (see screenshot)

**Expected behavior**
The workspace is displayed full screen like the application naps2

**Screenshots**
![2024-09-19_110555_naps2](https://github.com/user-attachments/assets/6d55bb92-ee48-4f88-aefa-d6d9518185ea)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version of naps2 7.5.1.0 in french

**Comment by yoyoweb** [comment]
After clicking on the windows display button
![2024-09-19_111844_naps2](https://github.com/user-attachments/assets/bfe672a0-c55c-4de3-b26d-388563d712f3)

and clicking on the full screen button,
![2024-09-19_111932_naps2](https://github.com/user-attachments/assets/7f1ce5e2-24f9-4196-ae13-a7da6132efad)

then it's as expected :
![2024-09-19_111730_naps2](https://github.com/user-attachments/assets/7d984332-2257-46a5-b46c-38c489da6c12)

**Comment by cyanfish** [comment]
This should be fixed in [8.0b1](https://www.naps2.com/download).

**Comment by yoyoweb** [comment]
> This should be fixed in [8.0b1](https://www.naps2.com/download).

Well it's better in 8.0b1 but the behaviour is different. The buttons are not displayed with margin, they are "cut" by  the frame of the windows
![2024-10-07_naps2](https://github.com/user-attachments/assets/c47df0cb-bd50-4841-a7a3-2e085f3f652f)

Then it's ok when I resize the windows of the application
![2024-10-07_184726_naps2](https://github.com/user-attachments/assets/d7f8582a-5b5a-406b-aff0-9f07fcdb6b13)

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by cyanfish** [comment]
The 7.5.2 issue should be fixed in [7.5.3](https://www.naps2.com/download).

**Comment by yoyoweb** [comment]
Thanks @cyanfish I've tested it with version 8.0.2.0 and the display works without issue.
