### ISSUE TITLE
Scansione alternata per Scanner solo Fronte (un lato) // Alternate scanning for Single Sided Scanner (one side)

### ISSUE THREAD

**Issue by daidardi** [cyanfish/naps2#454]
**[ITA]**
Vorrei suggerire un'opzione, magari configurabile da "profilo", che permetta la scansione fronte/retro con perfiriche scanner che possono scansionare solo da un lato.

Per esempio:
5 fogli fonte/retro

NAPS2 dovrebbe fare una prima scansione numerando i le "pagine" (non i "fogli") come 1-3-5. Successivamente consentire una seconda scansione, numerandoli 2-4-6.
Alla fine, NAPS2 dovrebbe riordinare le pagine.

--

**[ENG]** _(Google translator)_
I would like to suggest an option, perhaps configurable from "profile", which allows double-sided scanning with scanner devices that can only scan from one side.

For example:
5 sheets source/back

NAPS2 should do a first scan numbering the "pages" (not "sheets") as 1-3-5. Then allow a second scan, numbering them 2-4-6.
Finally, NAPS2 should reorder the pages.

**Comment by cyanfish** [comment]
You can do this by scanning then clicking "Interleave" under the "Reorder" menu.
