### ISSUE TITLE
Add the "Collapse to Tray" function

### ISSUE THREAD

**Issue by amber8706** [cyanfish/naps2#462]
ESCL scanning only works if NAPS is running. Thus, NAPS should be able to run in the background. Add the menu item "Hide the button from the taskbar when minimized". Thus, the NAPS icon will be near the clock, and not on the taskbar.

Also, for convenience, add the "Run NAPS at login" setting.

**Comment by cyanfish** [comment]
See https://github.com/cyanfish/naps2/issues/253

**Comment by amber8706** [comment]
"Collapse to Tray" is faster to do than to develop a service. Also, you do not need administrative rights for this.
