### ISSUE TITLE
7.0B2 can't select a twain source

### ISSUE THREAD

**Issue by Speedy1496** [cyanfish/naps2#47]
Hello,
I'm using NAPS2  on windows 11 22h2 last release

When I when to add a new source, I have an error when I push the select Buton.

Profiles --> New --> Twain --> Select

I have the following error on the text file in data

Thank you

2023-01-03 21:39:21.4026 20716 An error occurred that caused the application to close. System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   à System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   à NAPS2.Serialization.XmlSerializer.DecimalSerializer.Deserialize(XElement element)
   à NAPS2.Serialization.CustomXmlSerializer`1.DeserializeObject(XElement element, Type type)
   à NAPS2.Serialization.XmlSerializer.DeserializeInternalNonNull(XElement element, Type type)
   à NAPS2.Serialization.XmlSerializer.DeserializeInternalNonNull(XElement element, Type type)
   à NAPS2.Serialization.XmlSerializer`1.DeserializeFromXElement(XElement element)
   à NAPS2.Serialization.SerializerExtensions.DeserializeFromBytes[T](ISerializer`1 serializer, Byte[] bytes)
   à NAPS2.Scan.Internal.ScanOptionsValidator.ValidateAll(ScanOptions options, ScanningContext scanningContext, Boolean requireDevice)
   à NAPS2.Scan.ScanController.<GetDeviceList>d__9.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à NAPS2.Scan.ScanPerformer.<PromptForDevice>d__19.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à NAPS2.Scan.ScanPerformer.<PromptForDevice>d__11.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à NAPS2.EtoForms.Ui.EditProfileForm.<ChooseDevice>d__44.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by cyanfish** [comment]
This should be fixed in [7.0b3](https://www.naps2.com/download).
