### ISSUE TITLE
Enlarge/resize scanned preview window

### ISSUE THREAD

**Issue by MVECoder** [cyanfish/naps2#470]
Somewhere around v7.5.0 the preview window, where you see what's been scanned, was decreased from full-window to partial.  It cannot be resized.  On a large monitor, this makes working with multiple scanned pages more tedious and time-consuming.

![image](https://github.com/user-attachments/assets/c27bd3e8-4242-4918-a27b-c2c6c67e973d)

If the old preview cannot be readopted, adding a setting to scale with the window would be helpful.

**Comment by cyanfish** [comment]
See #453
