### ISSUE TITLE
NAPS2 7.5.2 & 8.0b1 crashes when opened (Fedora 41)

### ISSUE THREAD

**Issue by slarti-zak** [cyanfish/naps2#485]
**Describe the bug**
 NAPS2 7.5.2 & 8.0b1 crashes when trying to launch it.

**To Reproduce**

1. Open a terminal an type `naps2`
2. See error

**Expected behavior**
NAPS2 opens without crashing.

**Screenshots**
*7.5.2*
![image](https://github.com/user-attachments/assets/bc45e891-1371-4914-a2b8-8f928204b718)

*8.0b1*
![image](https://github.com/user-attachments/assets/570d5243-1bf6-40fe-bfbf-05300a30fec5)

**Desktop (please complete the following information):**
 - OS: Fedora (with Gnome)
 - Version 41
 - gdk-pixbuf2: 2.42.12

**Additional context**
Seems similar to #373 but installed gdk-pixbuf2 version is 2.42.12

**Comment by cyanfish** [comment]
This should be fixed in [7.5.3](https://www.naps2.com/download).
