### ISSUE TITLE
NAPS 7.5.2 maximized window is shown incompletely when opened as maximized

### ISSUE THREAD

**Issue by TobiasKnauss** [cyanfish/naps2#487]
**Describe the bug**
See screenshot below.
NAPS was opened as maximized (because it was maximized when it was closed before). The inner part of the window is however not adapted to the maximized size, and therefore partly hidden.

**To Reproduce**
1. Start NAPS
2. Maximize the window
3. Close NAPS
4. Start NAPS again

**Expected behavior**
The GUI elements in the window should all be visible

**Screenshots**
![NAPS 7 5 2 Fullscreen incomplete](https://github.com/user-attachments/assets/63fcb575-80cd-465b-a671-353cc6818b11)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home (23H2)
 - Version 7.5.2 (was also present in previous version(s).

**Comment by githubuser181226** [comment]
Hi. The same thing happening for me. Using Win7 x64 and Win10 x64. Small but very annoying bug.

**Comment by cyanfish** [comment]
This should be fixed in [7.5.3](https://www.naps2.com/download).
