### ISSUE TITLE
7.0.3 Scanned doc PDF has some pages with colours inverted

### ISSUE THREAD

**Issue by bebobebo** [cyanfish/naps2#52]
Windows 11

Opened a scanned PDF to work on and found that 3pp render with colours inverted. They do not render as such in 3 PDF viewers I tested, including Edge browser.
[KRZYZANOWSKA Op.13 Serenade (D'Editions Artistiques).pdf](https://github.com/cyanfish/naps2/files/10378915/KRZYZANOWSKA.Op.13.Serenade.D.Editions.Artistiques.pdf)

Side note: Invert colours might be a useful image tool, and it's straightforward.

**Comment by cyanfish** [comment]
This should be fixed in [7.0b4](https://www.naps2.com/download), please try and see if it works.

**Comment by bebobebo** [comment]
confirmed fixed in 7.0b4
