### ISSUE TITLE
[7.0.3.0] Framework exception (DragDrop-Registration)

### ISSUE THREAD

**Issue by akuropka** [cyanfish/naps2#58]
Upon scanning an image the following exception is thrown by .NET framework:
> Informationen über das Aufrufen von JIT-Debuggen
> anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
> 
> ************** Ausnahmetext **************
> System.InvalidOperationException: Fehler bei der DragDrop-Registrierung ---> System.Threading.ThreadStateException: Für den aktuellen Thread muss der STA-Modus (Single Thread Apartment) festgelegt werden, bevor OLE-Aufrufe ausgeführt werden können. Stellen Sie sicher, dass die Hauptfunktion mit STAThreadAttribute gekennzeichnet ist.
>    bei System.Windows.Forms.Control.SetAcceptDrops(Boolean accept)
>    --- Ende der internen Ausnahmestapelüberwachung ---
>    bei System.Windows.Forms.Control.SetAcceptDrops(Boolean accept)
>    bei System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
>    bei System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
>    bei System.Windows.Forms.Control.WmCreate(Message& m)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.Form.WmCreate(Message& m)
>    bei Eto.WinForms.Forms.EtoFormBase.WndProcImpl(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9105.0 built by: NET481REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> NAPS2
>     Assembly-Version: 7.0.3.0.
>     Win32-Version: 7.0.3.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/NAPS2.exe.
> ----------------------------------------
> NAPS2.Lib.WinForms
>     Assembly-Version: 7.0.3.0.
>     Win32-Version: 7.0.3.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/NAPS2.Lib.WinForms.DLL.
> ----------------------------------------
> Eto
>     Assembly-Version: 2.7.0.0.
>     Win32-Version: 2.7.8333.40430.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/Eto.DLL.
> ----------------------------------------
> netstandard
>     Assembly-Version: 2.0.0.0.
>     Win32-Version: 4.8.9032.0.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll.
> ----------------------------------------
> NAPS2.Lib
>     Assembly-Version: 7.0.3.0.
>     Win32-Version: 7.0.3.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/NAPS2.Lib.DLL.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9065.0 built by: NET481REL1LAST_C.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> Autofac
>     Assembly-Version: 6.4.0.0.
>     Win32-Version: 6.4.0.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/Autofac.DLL.
> ----------------------------------------
> Microsoft.Bcl.AsyncInterfaces
>     Assembly-Version: 6.0.0.0.
>     Win32-Version: 6.0.21.52210.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/Microsoft.Bcl.AsyncInterfaces.DLL.
> ----------------------------------------
> System.Threading.Tasks.Extensions
>     Assembly-Version: 4.2.0.1.
>     Win32-Version: 4.6.28619.01.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/System.Threading.Tasks.Extensions.DLL.
> ----------------------------------------
> NAPS2.Sdk
>     Assembly-Version: 7.0.3.0.
>     Win32-Version: 7.0.3.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/NAPS2.Sdk.DLL.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9075.0 built by: NET481REL1LAST_C.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0 built by: NET481REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> Eto.WinForms
>     Assembly-Version: 2.7.0.0.
>     Win32-Version: 2.7.8333.40445.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/Eto.WinForms.DLL.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9115.0 built by: NET481REL1LAST_B.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System.ValueTuple
>     Assembly-Version: 4.0.3.0.
>     Win32-Version: 4.6.26515.06.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/System.ValueTuple.DLL.
> ----------------------------------------
> NAPS2.Images
>     Assembly-Version: 7.0.3.0.
>     Win32-Version: 7.0.3.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/NAPS2.Images.DLL.
> ----------------------------------------
> System.Collections.Immutable
>     Assembly-Version: 6.0.0.0.
>     Win32-Version: 6.0.21.52210.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/System.Collections.Immutable.DLL.
> ----------------------------------------
> NAPS2.Images.Gdi
>     Assembly-Version: 7.0.3.0.
>     Win32-Version: 7.0.3.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/NAPS2.Images.Gdi.DLL.
> ----------------------------------------
> NLog
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.15.867.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/NLog.DLL.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0 built by: NET481REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0 built by: NET481REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> System.Data
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9110.0 built by: NET481REL1LAST_B.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
> ----------------------------------------
> System.ServiceModel
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0 built by: NET481REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll.
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0 built by: NET481REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
> ----------------------------------------
> Google.Protobuf
>     Assembly-Version: 3.21.9.0.
>     Win32-Version: 3.21.9.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/Google.Protobuf.DLL.
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly-Version: 0.0.0.0.
>     Win32-Version: 4.8.9105.0 built by: NET481REL1LAST_C.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll.
> ----------------------------------------
> System.Diagnostics.DiagnosticSource
>     Assembly-Version: 4.0.5.0.
>     Win32-Version: 4.700.20.21406.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/System.Diagnostics.DiagnosticSource.DLL.
> ----------------------------------------
> System.ComponentModel.Composition
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll.
> ----------------------------------------
> NAPS2.Lib.resources
>     Assembly-Version: 7.0.3.0.
>     Win32-Version: 7.0.3.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/de/NAPS2.Lib.resources.DLL.
> ----------------------------------------
> System.Xml.Linq
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0 built by: NET481REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
> ----------------------------------------
> GrpcDotNetNamedPipes
>     Assembly-Version: 2.0.0.0.
>     Win32-Version: 2.0.0.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/GrpcDotNetNamedPipes.DLL.
> ----------------------------------------
> Grpc.Core.Api
>     Assembly-Version: 2.0.0.0.
>     Win32-Version: 2.49.0.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/Grpc.Core.Api.DLL.
> ----------------------------------------
> Microsoft.WindowsAPICodePack.Shell
>     Assembly-Version: 1.1.4.0.
>     Win32-Version: 1.1.4.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/Microsoft.WindowsAPICodePack.Shell.DLL.
> ----------------------------------------
> Microsoft.WindowsAPICodePack
>     Assembly-Version: 1.1.4.0.
>     Win32-Version: 1.1.4.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/Microsoft.WindowsAPICodePack.DLL.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0 built by: NET481REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> Accessibility
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0 built by: NET481REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
> ----------------------------------------
> System.Runtime.InteropServices.RuntimeInformation
>     Assembly-Version: 4.0.2.0.
>     Win32-Version: 4.6.26011.01.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/System.Runtime.InteropServices.RuntimeInformation.DLL.
> ----------------------------------------
> Windows.ApplicationModel
>     Assembly-Version: 255.255.255.255.
>     Win32-Version: 10.0.10011.16384.
>     CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.ApplicationModel.winmd.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.9032.0 built by: NET481REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------
> zxing
>     Assembly-Version: 0.16.8.0.
>     Win32-Version: 0.16.8.0.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/zxing.DLL.
> ----------------------------------------
> System.Memory
>     Assembly-Version: 4.0.1.2.
>     Win32-Version: 4.6.31308.01.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/System.Memory.DLL.
> ----------------------------------------
> System.Runtime.CompilerServices.Unsafe
>     Assembly-Version: 6.0.0.0.
>     Win32-Version: 6.0.21.52210.
>     CodeBase: file:///C:/Program%20Files/NAPS2/lib/System.Runtime.CompilerServices.Unsafe.DLL.
> ----------------------------------------
> 
> ************** JIT-Debuggen **************
> Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
> Konfigurationsdatei der Anwendung oder des Computers
> (machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
> Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.
> 
> Zum Beispiel:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
> Ausnahmen an den JIT-Debugger gesendet, der auf dem
> Computer registriert ist, und nicht in diesem Dialogfeld behandelt.
> 

Screencast:
https://user-images.githubusercontent.com/22570574/215283994-802ee798-bb14-4ef9-9147-562e3db6f2ed.mp4

**Comment by cyanfish** [comment]
Does this work normally with version 6.1.2?

**Comment by akuropka** [comment]
Yes.

**Comment by cyanfish** [comment]
Can you try this test version and see if there's any difference? [naps2-7.0b3-testtwain.zip](https://github.com/cyanfish/naps2/files/10609191/naps2-7.0b3-testtwain.zip)

**Comment by akuropka** [comment]
Hello @cyanfish,
the issue persists. I tried a little bit around and I can break it down to the AutoSave festure which causes the bug.
If I choose to proceed at the error message and select then processing in background the task seems to get completed as expected. An errorlog file is not created.
I hope this helps. Thank you for your support.

**Comment by cyanfish** [comment]
This should be fixed in [7.0b4](https://www.naps2.com/download), please try and see if it works.

**Comment by akuropka** [comment]
perfect, thanks.
