### ISSUE TITLE
Unable to work with "TWAIN2 FreeImage Software Scanner"

### ISSUE THREAD

**Issue by fvoronin** [cyanfish/naps2#68]
**Describe the bug**
NAPS2 doesn't see the "TWAIN2 FreeImage Software Scanner" virtual scanner. But NTwain (https://github.com/soukoku/ntwain) does.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the "TWAIN2 FreeImage Software Scanner".
  Link to installers can be found at https://github.com/Dynamsoft/Dynamic-Web-TWAIN/blob/master/README.md#a-virtual-scanner or direct link is https://download.dynamsoft.com/tool/twainds.win32.installer.2.1.3.msi
2. Try to creating a new profile with that TWAIN virtual scanner.
3. See error "No scanning device was found".
![image](https://user-images.githubusercontent.com/1442281/216551975-46bc4082-a45b-4798-8d1d-8c76deb7f692.png)

**Expected behaviour**
1. The "Select Source" window appears with "TWAIN2 FreeImage Software Scanner" in the list.
2. Can take images from that virtual scanner.
![image](https://user-images.githubusercontent.com/1442281/216552333-66f43d91-af3c-494d-a99e-bb5f20275e24.png)

And how it looks in the NTwain sample application:
![image](https://user-images.githubusercontent.com/1442281/216552721-07f8e04d-4f7c-42dc-b990-ba8b3546a7ed.png)

**Desktop:**
 - OS: Windows 10
 - Version 7.0b3

**Additional context**
"TWAIN2 FreeImage Software Scanner" helps to create additional software based on NAPS2.Sdk. Support for this scanner will be very useful.

**Comment by cyanfish** [comment]
This is included in 7.0b5.
