### ISSUE TITLE
UWP OCR

### ISSUE THREAD

**Issue by lollita** [cyanfish/naps2#72]
Replace Tesseract dependencies using [UWP OCR](https://docs.microsoft.com/en-us/uwp/api/windows.media.ocr) in windows 10 C#.

**Comment by cyanfish** [comment]
Is there a quality or performance benefit for this OCR? What kind of language selection is there (compared to Tesseract's 100+)?

**Comment by lollita** [comment]
avoid Tesseract dependecie and 50 GB. See ShareX.

**Comment by cyanfish** [comment]
The Tesseract dependency is 3MB in the base download (7MB extracted), plus the language data which varies, e.g. English is a 12MB download (26MB extracted). I consider that minimal and am much more concerned with functionality.

In any case we can't get rid of the Tesseract dependency as we support Windows 7, not to mention Mac and Linux.
