### ISSUE TITLE
Batch Scan profile issues

### ISSUE THREAD

**Issue by AltoRetrato** [cyanfish/naps2#73]
**Describe the bug**
When I start a Batch Scan, NAPS2 automatically select (and uses) the last used profile for Batch Scan, instead of selecting the default profile. And even if I select another profile, it will still use the previously selected profile.

**To Reproduce**
1. Create two profiles: one with 24bpp and another with 1bpp.
![Clipboard01](https://user-images.githubusercontent.com/22997468/216826497-0c7cf011-73a6-42d4-9c98-16839f7be08d.png)

2. Open Batch Scan and select a 1bpp profile.
![Clipboard02](https://user-images.githubusercontent.com/22997468/216826508-73d9d517-378b-4d17-820e-5c4e4654585b.png)

3. Put a color photo on the scanner and click Start to scan it, then close the Batch Scan.
4. Check the image - unless the last profile used was already 1bpp, the image is probably looking not like 1bpp at all, but like the previously used profile. The following image was produced with the 1bpp profile selected in the Batch Scan windows (but it produced a 24bpp image, as it was the profile I was previously using):
![scanned as 1bpp 3](https://user-images.githubusercontent.com/22997468/216826522-fb9aaed8-29a1-4271-9a44-1b26c5af7d7d.jpg)

5. Open Batch Scan and select a 24bpp profile.
![Clipboard04](https://user-images.githubusercontent.com/22997468/216826539-12075fc5-7305-41f0-892b-34ae6951dfb2.png)

6. Do a scan of a color photo or print and close the Batch Scan.
7. Check the image - even though it was created with the 24bpp profile, it clearly used the 1bpp, as in the following image:
![scanned as 24bpp](https://user-images.githubusercontent.com/22997468/216826545-25d40486-14f1-48e9-944d-9710edfb643b.jpg)

**Expected behavior**
I expected two things that didn't happen:
1. Batch Scan to use the default profile
2. Batch Scan to use the currently selected profile in the Batch Scan window (it always used the previously used profile)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 7.0b3

**Comment by cyanfish** [comment]
The delayed update should be fixed in [7.0b4](https://www.naps2.com/download), please try and see if it works.

Selected the last-used profile for batch scanning instead of the default profile is intended behavior, as the idea is that you may use different profiles for batch and non-batch scanning.
