### ISSUE TITLE
NAPS2.Console --progress option is not working

### ISSUE THREAD

**Issue by mrbastian** [cyanfish/naps2#83]
The NAPS2.Console command includes the option "--progress" with description "Display a graphical window for scanning progress."

I've tried this with 7.0b4, and it does not appear to do anything. Command line:
NAPS2.Console.exe --profile BW300 --output c:\users\mbastian\downloads\x.tif --force --progress --verbose

Desktop OS: Windows 11 64-bit

**Comment by cyanfish** [comment]
This should be fixed in [7.1.1](https://www.naps2.com/download).
