### ISSUE TITLE
Feature Request: Manual two-sided printing 'reorder' option

### ISSUE THREAD

**Issue by mrfaptastic** [cyanfish/naps2#84]
My scanner doesn't support double-sided scanning, and I think a useful feature would be to make it such the 'reorder' option in NAPS2 solves for this.

Example:

* My scanner has an automatic document feeder (ADF)
* I needed to scan 9 pages (which were printed on both sides of A4 / double sided -> five (5) physical sheets).

Approach:
* I fed into the ADF front side top first to scan pages 1, 3, 5, 7, 9 
* Then flip over the stack of paper and scan the other side top first... pages 10 (blank), 8, 6, 4, 2

Feature wanted:
* New re-order option to accomodate this approach. That is turn the scanned order of pages:
```
1, 2, 3, 4, 5, 6, 7, 8, 9, 10 
(where 1, 2, 3 are actually pages 1, 3, 5 ... etc in the phyiscal document)
(where 6, 7, 8 are actually pages <blank>, 8, 6 ... etc)
```
to 
```
1, 10, 2, 9, 3, 8, 4, 7, 5, 6

```

The constraint being, a person must first scan all 'front side' pages, then 'back side' pages, and not then mess with the order in NAPS2.

**Comment by mrfaptastic** [comment]
By the way, thanks for making such a great app. Much better than the junk that gets shipped with the usual printers and scanners.

**Comment by cyanfish** [comment]
The "Alternative Interleave" option should do this. Though it definitely could be described better.

**Comment by mrfaptastic** [comment]
Ah ok. Yeah, it's not obvious, and also, once I had tried using the wrong reorder, it as too late as everything had already been messed up.

**Comment by grandmastermarco** [comment]
it would be awesome to be able to preselect which type of reodering the program should do (some kind of default option).
i always forget which type of reorder i need for my particular scanner ;)

**Comment by TheRealYasri** [comment]
I just helped my mother do this for her work(nonprofit). If you scan like the OP said then...

select the back 50% of pages scanned. So if its 20 pages, you select 11-20.
reorder -> reverse -> selected 
reorder -> Interleave

It puts the scans in the same order as duplex scan would. Would be nice to have a dialog to do this for the scanner, if it does not support it.

**Comment by cyanfish** [comment]
@TheRealYasri "Alternative Interleave" will do this in one go.

**Comment by TheRealYasri** [comment]
@cyanfish Yeah your right, thought I tried that reorder combination when I was trying them all to see what they did. Maybe a tooltip to explain it. 

Reorders all scans (Example has 20 scans)
1, 20, 2, 19, 3, 18, 4, 17, etc

**Comment by cyanfish** [comment]
Tracking "Manual Duplex" rework in #303
