### ISSUE TITLE
7.0b4 - Profiles won't allow selection of default

### ISSUE THREAD

**Issue by srdlgh** [cyanfish/naps2#85]
Either I'm missing something, or Profiles in 7.0b4 always sets the last profile as default -- and doesn't provide for a way to set any other.

**Comment by cyanfish** [comment]
To match Windows, the Linux UI does need to be updated with (a) a context menu in the profiles window, and (b) a default profile indicator in the Scan dropdown. Choosing a different profile in the Scan dropdown will change the default though.
