### ISSUE TITLE
Linux console

### ISSUE THREAD

**Issue by msharaf56** [cyanfish/naps2#87]
I've installed naps2 flatpak 7.0b4 on my ubuntu v 22 , the gui works fine but the batch processing is not working. I have the following command flatpak run com.naps2.Naps2 NAPS2.Console.exe -a --progress -p ScanFlat when I started it , NAPS2 GUI opens and I have the following error message Error, libnotify.so.4 was not found, notifications won't be displayed. I checked libnotify is installed on my machine. Can any one help me? Thanks

**Comment by cyanfish** [comment]
I need to update the doc for Linux (and Mac), but you should be able to run like this:
`flatpak run com.naps2.Naps2 console -a --progress -p ScanFlat`
(Though --progress [currently](https://github.com/cyanfish/naps2/issues/83) isn't working)
