### ISSUE TITLE
7.0b4 Linux - Add file extensions on save

### ISSUE THREAD

**Issue by srdlgh** [cyanfish/naps2#89]
Maybe a bug -- or maybe just something that hasn't made it to the top of the to-do list yet.

**Comment by cyanfish** [comment]
Can you be more specific? They seem to be working for me.

**Comment by srdlgh** [comment]
Ben --

It looks like I should have sent that report to the Journal of
Irreproducible Results -- it does seem to work.  Possibly I munged it
somewho working on the macros.  I'll let you know if it appears again.

I think I can reproduce this one, though.  Saving as PDF in 7.0b Linux
doesn't seem to add the ".pdf" suffix automatically if not already present.

--Steve R

**Comment by cyanfish** [comment]
Extensions should now be added when you click Save in the latest [beta version](https://www.naps2.com/download) (7.0b5).
