### ISSUE TITLE
pdf to odt conversion (retaining text formatting)

### ISSUE THREAD

**Issue by kintaro1981** [cyanfish/naps2#99]
Hello,

is pdf to odt conversion (retaining text formatting) feature going to be included in NAPS2 in the next future?

**Comment by cyanfish** [comment]
Hi, I don't currently intend to add support for other filetypes like .docx or .odt. Why do you want this in NAPS2?

**Comment by kintaro1981** [comment]
Because I would like to adopt NAPS2  as main app to convert from pdf avoiding to use closed source or online services. I think that NAPS2 in combination with PdfSam (to join/split etc. pages) can became “the pdf solution”.

Right now we (a medium Italian municipality) are already using NAPS2 to convert scanned pdf into searchable and readable from screen readers for impaired eye people and we are trying to find, without success, an open-source project able to convert scanned (and not scanned) pdf to odt retaining text formatting.

Thank you for your time.
Regards

**Comment by cyanfish** [comment]
Have you tried using .docx as an intermediary format?
https://github.com/dothinking/pdf2docx
https://stackoverflow.com/questions/21845789/how-to-convert-docx-to-odt-with-libreoffice-on-ubuntu-bash

**Comment by cyanfish** [comment]
In any case, while it would be nice in principle to have support for more formats, this is beyond the scope of what I'm planning on building into NAPS2.
